In [2]:
from datetime import datetime, date
from pandas import DataFrame as df
from pathlib import Path
import pandas as pd
from os import path
import datetime
import time
import os

pd.options.display.float_format = "{:,.2f}".format

from mthly_hedge_file import HedgeFile

%load_ext autoreload
%autoreload 2

In [3]:
file_dir = r'C:\Users\S0053071\Repos\Orion_Process_Backup\HdgRpts_Archive'
file_0 = '10_2024_HEDGE_TRUE_UP.TXT'
file_1 = '11_2024_HEDGE_ORIG.TXT'
file_2 = '11_2024_HEDGE_TRUE_UP.TXT'
file_3 = '12_2024_HEDGE_ORIG.TXT'
file_4 = '12_2024_HEDGE_TRUE_UP.TXT'

file_path_0 = os.path.join(file_dir, file_0)
file_path_1 = os.path.join(file_dir, file_1)
file_path_2 = os.path.join(file_dir, file_2)
file_path_3 = os.path.join(file_dir, file_3)
file_path_4 = os.path.join(file_dir, file_4)

In [4]:
oct_24_true = HedgeFile(file_path_0)
nov_24_orig = HedgeFile(file_path_1)
nov_24_true = HedgeFile(file_path_2)
dec_24_orig = HedgeFile(file_path_3)
dec_24_true = HedgeFile(file_path_4)

Reading in Helper Dataframes (used for static lookups to obtain values for related fields)
REMINDER TO UPDATE NEW BUDGET INFO in Static_Assumptions Folder for ProductDetailsByHedgeDate.csv!!!
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\HedgeDates.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\HdgFctrLU.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\CoPlanInd_to_Prod.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\Indicator_to_FundName.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\ProductDetailsByHedgeDate.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\Orion_IUL_Policies.csv
Converting Static Assum DataFrame Dates to Datetime.Date
Attempting to extract date from hedge file since date parameter was not provided
Hedge Date set to 2024-10-01
Based on the hedge file name, this is a true-up file
Hedge File Path provided as a non-directory for new hedges on 2024-10-01
Hedge File Path set to: C:\Users\S0053071\Repos\Orion_Process_Backup\HdgRpts_Archive\10_2024_HEDGE_TRUE_UP.TXT
Hedge TrueUp is set to True
Reading in Helper Dataframes (used for static lookups to obtain values for related fields)
REMINDER TO UPDATE NEW BUDGET INFO in Static_Assumptions Folder for ProductDetailsByHedgeDate.csv!!!
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\HedgeDates.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\HdgFctrLU.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\CoPlanInd_to_Prod.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\Indicator_to_FundName.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\ProductDetailsByHedgeDate.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\Orion_IUL_Policies.csv
Converting Static Assum DataFrame Dates to Datetime.Date
Attempting to extract date from hedge file since date parameter was not provided
Hedge Date set to 2024-11-01
TRUE_UP was not found in the file name and no cmd line arg was provided, so assuming this is not the true-up version of the file!
Hedge File Path provided as a non-directory for new hedges on 2024-11-01
Hedge File Path set to: C:\Users\S0053071\Repos\Orion_Process_Backup\HdgRpts_Archive\11_2024_HEDGE_ORIG.TXT
Hedge TrueUp is set to False
Reading in Helper Dataframes (used for static lookups to obtain values for related fields)
REMINDER TO UPDATE NEW BUDGET INFO in Static_Assumptions Folder for ProductDetailsByHedgeDate.csv!!!
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\HedgeDates.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\HdgFctrLU.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\CoPlanInd_to_Prod.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\Indicator_to_FundName.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\ProductDetailsByHedgeDate.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\Orion_IUL_Policies.csv
Converting Static Assum DataFrame Dates to Datetime.Date
Attempting to extract date from hedge file since date parameter was not provided
Hedge Date set to 2024-11-01
Based on the hedge file name, this is a true-up file
Hedge File Path provided as a non-directory for new hedges on 2024-11-01
Hedge File Path set to: C:\Users\S0053071\Repos\Orion_Process_Backup\HdgRpts_Archive\11_2024_HEDGE_TRUE_UP.TXT
Hedge TrueUp is set to True
Reading in Helper Dataframes (used for static lookups to obtain values for related fields)
REMINDER TO UPDATE NEW BUDGET INFO in Static_Assumptions Folder for ProductDetailsByHedgeDate.csv!!!
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\HedgeDates.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\HdgFctrLU.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\CoPlanInd_to_Prod.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\Indicator_to_FundName.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\ProductDetailsByHedgeDate.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\Orion_IUL_Policies.csv
Converting Static Assum DataFrame Dates to Datetime.Date
Attempting to extract date from hedge file since date parameter was not provided
Hedge Date set to 2024-12-02
TRUE_UP was not found in the file name and no cmd line arg was provided, so assuming this is not the true-up version of the file!
Hedge File Path provided as a non-directory for new hedges on 2024-12-02
Hedge File Path set to: C:\Users\S0053071\Repos\Orion_Process_Backup\HdgRpts_Archive\12_2024_HEDGE_ORIG.TXT
Hedge TrueUp is set to False
Reading in Helper Dataframes (used for static lookups to obtain values for related fields)
REMINDER TO UPDATE NEW BUDGET INFO in Static_Assumptions Folder for ProductDetailsByHedgeDate.csv!!!
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\HedgeDates.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\HdgFctrLU.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\CoPlanInd_to_Prod.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\Indicator_to_FundName.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\ProductDetailsByHedgeDate.csv
Reading Data from g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\Orion_IUL_Policies.csv
Converting Static Assum DataFrame Dates to Datetime.Date
Attempting to extract date from hedge file since date parameter was not provided
Hedge Date set to 2024-12-02
Based on the hedge file name, this is a true-up file
Hedge File Path provided as a non-directory for new hedges on 2024-12-02
Hedge File Path set to: C:\Users\S0053071\Repos\Orion_Process_Backup\HdgRpts_Archive\12_2024_HEDGE_TRUE_UP.TXT
Hedge TrueUp is set to True

In [5]:
oct_24_true.load_hedgefile()
nov_24_orig.load_hedgefile()
nov_24_true.load_hedgefile()
dec_24_orig.load_hedgefile()
dec_24_true.load_hedgefile()

Importing Hedge Txt File

g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\mthly_hedge_file.py:320: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  hedgefile_df = pd.read_csv(self.hedge_file, index_col=False, header=None, names=hedgefile_colnames, skipfooter=2, engine='python', low_memory=True)

Time Reading Hedge File: 0 mins 6 secs
Merging Hedge File w/ Helper Files to Add Additional Fields
Finished...Time Merging Hedge File: 0 mins 1 secs
Importing Hedge Txt File

g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\mthly_hedge_file.py:320: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  hedgefile_df = pd.read_csv(self.hedge_file, index_col=False, header=None, names=hedgefile_colnames, skipfooter=2, engine='python', low_memory=True)

Time Reading Hedge File: 0 mins 6 secs
Merging Hedge File w/ Helper Files to Add Additional Fields
Finished...Time Merging Hedge File: 0 mins 1 secs
Importing Hedge Txt File

g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\mthly_hedge_file.py:320: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  hedgefile_df = pd.read_csv(self.hedge_file, index_col=False, header=None, names=hedgefile_colnames, skipfooter=2, engine='python', low_memory=True)

Time Reading Hedge File: 0 mins 5 secs
Merging Hedge File w/ Helper Files to Add Additional Fields
Finished...Time Merging Hedge File: 0 mins 1 secs
Importing Hedge Txt File

g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\mthly_hedge_file.py:320: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  hedgefile_df = pd.read_csv(self.hedge_file, index_col=False, header=None, names=hedgefile_colnames, skipfooter=2, engine='python', low_memory=True)

Time Reading Hedge File: 0 mins 6 secs
Merging Hedge File w/ Helper Files to Add Additional Fields
Finished...Time Merging Hedge File: 0 mins 1 secs
Importing Hedge Txt File

g:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\mthly_hedge_file.py:320: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  hedgefile_df = pd.read_csv(self.hedge_file, index_col=False, header=None, names=hedgefile_colnames, skipfooter=2, engine='python', low_memory=True)

Time Reading Hedge File: 0 mins 5 secs
Merging Hedge File w/ Helper Files to Add Additional Fields
Finished...Time Merging Hedge File: 0 mins 1 secs

In [18]:
hedgefile_colnames = ['CompID', 'PolicyNum', 'Plan', 'IssueDate', 'Indicator', 'Tranx', 'Rev', 'Dept_Desk', 'Entry_Date', 'AsOf_Date', 'Base_Liab_Ntnl', 'Part', 'Cap', 'MGIR_(Cap)', 'Floor', 'Spec_Rate', 'Spread', 'Asset_Charge', 'Multiplier']

status_added_date = date(2024, 10, 1)

if hdgfile.hedge_date >= status_added_date:
    hedgefile_colnames.append('Status')


# Read hedge file
hedgefile_df = pd.read_csv(hdgfile.hedge_file, index_col=False, header=None, names=hedgefile_colnames, skipfooter=2, engine='python', low_memory=True)

# Add HedgeDate to DataFrame
hedgefile_df['HedgeDate'] = hdgfile.hedge_date

# Reminder to add HedgeDate to File and to date_cols below!
date_cols = ['HedgeDate', 'IssueDate', 'Entry_Date', 'AsOf_Date']
for date_col in date_cols:
    hedgefile_df[date_col] = pd.to_datetime(hedgefile_df[date_col]).dt.date

# Strip spaces out of 'PolicyNum', 'Plan', 'Tranx' and 'Indicator columns data
hedgefile_df['PolicyNum'] = hedgefile_df['PolicyNum'].str.strip()
hedgefile_df['Plan'] = hedgefile_df['Plan'].str.strip()
hedgefile_df['Tranx'] = hedgefile_df['Tranx'].str.strip()
hedgefile_df['Indicator'] = hedgefile_df['Indicator'].str.strip()

# Filter by 'Status' containing 'R' for 'RGA' reinsured if the hedge date is past the status_added_date, otherwise join to the Orion_IUL_Policies table by PolicyNum
if hdgfile.hedge_date >= status_added_date:
    hedgefile_df = hedgefile_df[hedgefile_df['Status'].str.contains('R')]
else:
    orion_pols = hdgfile.assum_dfs['Orion_IUL_Policies']
    orion_pols['PolicyNum'] = orion_pols['PolicyNum'].str.strip()
    hedgefile_df = hedgefile_df.merge(orion_pols, on='PolicyNum')

# Filter out 'Reversals' in 'Rev' column
hedgefile_df = hedgefile_df[hedgefile_df['Rev'].str.contains(' ')]

# Filter out 'Tranx' to only contain 'EXCHNGE TO'
hedgefile_df = hedgefile_df[hedgefile_df['Tranx'].str.contains('EXCHNGE TO')]

# Adjust Fields to Divide by 100
pct_fields = ['Floor', 'Spec_Rate', 'Spread', 'Part', 'Asset_Charge', 'Multiplier', 'Cap']
for fld in pct_fields:
    hedgefile_df[fld] = hedgefile_df[fld] / 100.0

# Update Cap Field for Digital Options (Based on 'Indicator' == 'INXSPC')
hedgefile_df['Cap'] = hedgefile_df.apply(lambda row: row['Spec_Rate'] if row['Indicator'] == 'INXSPC' else row['Cap'], axis=1)

C:\Users\S0053071\AppData\Local\Temp\ipykernel_33392\2102830589.py:10: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  hedgefile_df = pd.read_csv(hdgfile.hedge_file, index_col=False, header=None, names=hedgefile_colnames, skipfooter=2, engine='python', low_memory=True)

In [19]:
hedgefile_df

,CompID,PolicyNum,Plan,IssueDate,Indicator,Tranx,Rev,Dept_Desk,Entry_Date,AsOf_Date,...,Part,Cap,MGIR_(Cap),Floor,Spec_Rate,Spread,Asset_Charge,Multiplier,Status,HedgeDate
2,1,UE000006,1U145500,2016-06-23,INX150,EXCHNGE TO,,SWEEP,2024-11-01,2024-11-01,...,1.0000,0.0850,3.0000,0.0150,0.0000,0.0000,0.0000,0.0000,R,2024-11-01
3,1,UE000006,1U145500,2016-06-23,INXFEE,EXCHNGE TO,,SWEEP,2024-11-01,2024-11-01,...,1.0000,9.9999,999.9900,0.0000,0.0000,0.0800,0.0000,0.0000,R,2024-11-01
5,1,UE000006,1U145500,2016-06-23,INX150,EXCHNGE TO,,IFRIC,2024-11-01,2024-11-01,...,1.0000,0.0850,3.0000,0.0150,0.0000,0.0000,0.0000,0.0000,R,2024-11-01
7,1,UE000006,1U145500,2016-06-23,INXFEE,EXCHNGE TO,,IFRIF,2024-11-01,2024-11-01,...,1.0000,9.9999,999.9900,0.0000,0.0000,0.0800,0.0000,0.0000,R,2024-11-01
9,1,UE000011,1U145500,2016-05-09,INX150,EXCHNGE TO,,SWEEP,2024-11-01,2024-11-01,...,1.0000,0.0850,3.0000,0.0150,0.0000,0.0000,0.0000,0.0000,R,2024-11-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383133,26,UN011777,1U146900,2023-04-14,INDEX,EXCHNGE TO,,IFRIX,2024-11-01,2024-11-01,...,1.0000,0.0850,3.0000,0.0000,0.0000,0.0000,0.0000,0.0000,R,2024-11-01
383134,26,UN011856,1U146900,2023-09-06,INDEX,EXCHNGE TO,,SWEEP,2024-11-01,2024-11-01,...,1.0000,0.0850,3.0000,0.0000,0.0000,0.0000,0.0000,0.0000,R,2024-11-01
383135,26,UN011856,1U146900,2023-09-06,INXFEE,EXCHNGE TO,,SWEEP,2024-11-01,2024-11-01,...,1.0000,9.9999,999.9900,0.0000,0.0000,0.0775,0.0000,0.0000,R,2024-11-01
383136,26,UN012447,1U146900,2024-01-20,INDEX,EXCHNGE TO,,SWEEP,2024-11-01,2024-11-01,...,1.0000,0.0850,3.0000,0.0000,0.0000,0.0000,0.0000,0.0000,R,2024-11-01
383137,26,UN012998,1U146900,2023-10-26,INDEX,EXCHNGE TO,,SWEEP,2024-11-01,2024-11-01,...,1.0000,0.0850,3.0000,0.0000,0.0000,0.0000,0.0000,0.0000,R,2024-11-01

In [20]:
hdgfile.hedgefile_df = hedgefile_df

In [21]:
merged_hf_df = hdgfile.merge_dataframes()

Merging Hedge File w/ Helper Files to Add Additional Fields
Finished...Time Merging Hedge File: 0 mins 1 secs

In [22]:
merged_hf_df

,CompID,PolicyNum,Plan,IssueDate,Indicator,Tranx,Rev,Dept_Desk,Entry_Date,AsOf_Date,...,Asset_Charge,Multiplier,Status,HedgeDate,HdgFctr,Strike,Adj_Liab_Ntnl,Product_Detail,Product,Budget
0,1,UE000006,1U145500,2016-06-23,INX150,EXCHNGE TO,,SWEEP,2024-11-01,2024-11-01,...,0.0000,0.0000,R,2024-11-01,0.9500,1.0150,23.6075,IUL14,IUL,0.0383
1,1,UE000006,1U145500,2016-06-23,INXFEE,EXCHNGE TO,,SWEEP,2024-11-01,2024-11-01,...,0.0000,0.0000,R,2024-11-01,0.9500,1.0800,23.6075,IUL14,IUL,0.0360
2,1,UE000006,1U145500,2016-06-23,INX150,EXCHNGE TO,,IFRIC,2024-11-01,2024-11-01,...,0.0000,0.0000,R,2024-11-01,0.9500,1.0150,238.2885,IUL14,IUL,0.0383
3,1,UE000006,1U145500,2016-06-23,INXFEE,EXCHNGE TO,,IFRIF,2024-11-01,2024-11-01,...,0.0000,0.0000,R,2024-11-01,0.9500,1.0800,288.9710,IUL14,IUL,0.0360
4,1,UE000011,1U145500,2016-05-09,INX150,EXCHNGE TO,,SWEEP,2024-11-01,2024-11-01,...,0.0000,0.0000,R,2024-11-01,0.9500,1.0150,26.2580,IUL14,IUL,0.0383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180904,26,UN011777,1U146900,2023-04-14,INDEX,EXCHNGE TO,,IFRIX,2024-11-01,2024-11-01,...,0.0000,0.0000,R,2024-11-01,0.7600,1.0000,63.6348,IUL14NY,IUL14NY,0.0482
180905,26,UN011856,1U146900,2023-09-06,INDEX,EXCHNGE TO,,SWEEP,2024-11-01,2024-11-01,...,0.0000,0.0000,R,2024-11-01,0.7600,1.0000,276.0320,IUL14NY,IUL14NY,0.0482
180906,26,UN011856,1U146900,2023-09-06,INXFEE,EXCHNGE TO,,SWEEP,2024-11-01,2024-11-01,...,0.0000,0.0000,R,2024-11-01,0.7600,1.0775,276.0320,IUL14NY,IUL14NY,0.0372
180907,26,UN012447,1U146900,2024-01-20,INDEX,EXCHNGE TO,,SWEEP,2024-11-01,2024-11-01,...,0.0000,0.0000,R,2024-11-01,0.7600,1.0000,306.8652,IUL14NY,IUL14NY,0.0482
180908,26,UN012998,1U146900,2023-10-26,INDEX,EXCHNGE TO,,SWEEP,2024-11-01,2024-11-01,...,0.0000,0.0000,R,2024-11-01,0.7600,1.0000,8.2764,IUL14NY,IUL14NY,0.0482

In [23]:
merged_hf_df['Entry_Date'].unique()

array([datetime.date(2024, 11, 1), datetime.date(2024, 10, 2),
       datetime.date(2024, 10, 18), datetime.date(2024, 10, 11),
       datetime.date(2024, 10, 7), datetime.date(2024, 10, 21),
       datetime.date(2024, 10, 14), datetime.date(2024, 10, 4),
       datetime.date(2024, 10, 22), datetime.date(2024, 10, 17),
       datetime.date(2024, 10, 3), datetime.date(2024, 10, 29),
       datetime.date(2024, 10, 10), datetime.date(2024, 10, 31),
       datetime.date(2024, 10, 9), datetime.date(2024, 10, 28),
       datetime.date(2024, 10, 15), datetime.date(2024, 10, 24),
       datetime.date(2024, 10, 23), datetime.date(2024, 10, 25),
       datetime.date(2024, 10, 8), datetime.date(2024, 10, 16),
       datetime.date(2024, 10, 30)], dtype=object)

In [26]:
nov_24_ntnl, oct_24_ntnl = merged_hf_df[merged_hf_df['Entry_Date']==date(2024,11, 1)]['Base_Liab_Ntnl'].sum(), merged_hf_df[merged_hf_df['Entry_Date']!=date(2024,11, 1)]['Base_Liab_Ntnl'].sum()

In [33]:
print(f'Nov 1st Entry Date in 11_2024_HEDGE_TRUE_UP.txt is: {nov_24_ntnl:,.0f}')
print(f'October Entry Dates in 11_2024_HEDGE_TRUE_UP.txt is: {oct_24_ntnl:,.0f}')
print(f'Total Ntnl in 11_2024_HEDGE_TRUE_UP.txt is: {oct_24_ntnl + nov_24_ntnl:,.0f}')

Nov 1st Entry Date in 11_2024_HEDGE_TRUE_UP.txt is: 70,310,094
October Entry Dates in 11_2024_HEDGE_TRUE_UP.txt is: 2,882,187
Total Ntnl in 11_2024_HEDGE_TRUE_UP.txt is: 73,192,281

In [36]:
group_cols = ['HedgeDate', 'Indicator']
merged_hf_df[merged_hf_df['Entry_Date']!=date(2024,11, 1)].groupby(group_cols).agg({'PolicyNum': 'count', 'Base_Liab_Ntnl':'sum', 'Adj_Liab_Ntnl':'sum'})

                      PolicyNum  Base_Liab_Ntnl  Adj_Liab_Ntnl
HedgeDate  Indicator
2024-11-01 INDEX           1994       1,770,365      1,681,395
           INX150            62          17,377         16,509
           INXFEE           322         147,039        139,444
           INXHIM            60         766,967      1,165,790
           INXLOM            25          24,037         28,315
           INXSPC            18             966            917
           MARPRT            89         129,881        295,395
           NASIDX            54          25,555         24,278

In [7]:
group_cols = ['HedgeDate', 'Indicator']
oct_24_true_df = oct_24_true.hedgefile_df
nov_24_orig_df = nov_24_orig.hedgefile_df
nov_24_true_df = nov_24_true.hedgefile_df
dec_24_orig_df = dec_24_orig.hedgefile_df
dec_24_true_df = dec_24_true.hedgefile_df

In [67]:
# dec_24_orig_df.columns
desired_cols = ['CompID', 'PolicyNum', 'Plan', 'Product_Detail', 'Product', 'IssueDate', 'Indicator', 'Tranx', 'Dept_Desk', 'HedgeDate', 'Entry_Date', 'AsOf_Date', 'Cap', 'Strike', 'Base_Liab_Ntnl', 'Adj_Liab_Ntnl']
oct_24_true_df = oct_24_true_df[desired_cols]
nov_24_orig_df = nov_24_orig_df[desired_cols]
nov_24_true_df = nov_24_true_df[desired_cols]
dec_24_orig_df = dec_24_orig_df[desired_cols]
dec_24_true_df = dec_24_true_df[desired_cols]

In [ ]:
pd.Series(dec_24_orig_df['Entry_Date'].unique()).sort_values()

7     2024-11-04
6     2024-11-05
1     2024-11-06
18    2024-11-07
9     2024-11-08
14    2024-11-11
5     2024-11-12
13    2024-11-13
10    2024-11-14
3     2024-11-15
4     2024-11-18
8     2024-11-19
12    2024-11-20
16    2024-11-21
17    2024-11-22
2     2024-11-25
11    2024-11-26
15    2024-11-27
0     2024-12-02
dtype: object

In [21]:
pd.Series(dec_24_true_df['Entry_Date'].unique()).sort_values()

7     2024-11-04
6     2024-11-05
1     2024-11-06
18    2024-11-07
9     2024-11-08
14    2024-11-11
5     2024-11-12
13    2024-11-13
10    2024-11-14
3     2024-11-15
4     2024-11-18
8     2024-11-19
12    2024-11-20
16    2024-11-21
17    2024-11-22
2     2024-11-25
11    2024-11-26
15    2024-11-27
0     2024-12-02
dtype: object

In [28]:
# detailed_group_cols = ['HedgeDate', 'AsOf_Date', 'Entry_Date', 'Indicator']
detailed_group_cols = ['AsOf_Date', 'Entry_Date', 'Indicator']
dec_24_orig_df.groupby(detailed_group_cols).agg({'PolicyNum': 'count', 'Base_Liab_Ntnl':'sum', 'Adj_Liab_Ntnl':'sum'}).to_clipboard()

In [30]:
dec_24_true_df.groupby(detailed_group_cols).agg({'PolicyNum': 'count', 'Base_Liab_Ntnl':'sum', 'Adj_Liab_Ntnl':'sum'}).to_clipboard()

In [53]:
nov_24_orig_df[nov_24_orig_df['Entry_Date']==date(2024,11, 1)].groupby(group_cols).agg({'PolicyNum': 'count', 'Base_Liab_Ntnl':'sum', 'Adj_Liab_Ntnl':'sum'})

                      PolicyNum  Base_Liab_Ntnl  Adj_Liab_Ntnl
HedgeDate  Indicator
2024-11-01 INDEX          97632      47,842,139     45,306,861
           INX150          5530       3,242,577      3,066,804
           INXFEE         38255      11,266,938     10,687,643
           INXHIM         10581       2,559,868      3,890,999
           INXLOM          4328         855,545      1,007,832
           INXSPC          2237         385,052        364,146
           MARPRT          8020       2,340,587      5,331,830
           NASIDX          4535         868,143        824,735

In [54]:
nov_24_true_df[nov_24_true_df['Entry_Date']==date(2024,11, 1)].groupby(group_cols).agg({'PolicyNum': 'count', 'Base_Liab_Ntnl':'sum', 'Adj_Liab_Ntnl':'sum'})

                      PolicyNum  Base_Liab_Ntnl  Adj_Liab_Ntnl
HedgeDate  Indicator
2024-11-01 INDEX         101744      48,439,661     45,872,115
           INX150          5737       3,250,477      3,074,022
           INXFEE         39724      11,467,956     10,878,352
           INXHIM         11030       2,613,866      3,973,077
           INXLOM          4507         866,642      1,020,904
           INXSPC          2337         386,187        365,178
           MARPRT          8463       2,403,787      5,475,796
           NASIDX          4743         881,518        837,442

In [56]:
dec_24_orig_df[dec_24_orig_df['Entry_Date']!=date(2024,12,2)].groupby(group_cols).agg({'PolicyNum': 'count', 'Base_Liab_Ntnl':'sum', 'Adj_Liab_Ntnl':'sum'})

                      PolicyNum  Base_Liab_Ntnl  Adj_Liab_Ntnl
HedgeDate  Indicator
2024-12-02 INDEX           1451       1,125,067      1,067,165
           INX150            51          11,687         11,103
           INXFEE           235          98,376         93,405
           INXHIM            63         106,133        161,322
           INXLOM            21           2,577          3,036
           INXSPC            14             441            419
           MARPRT            87         223,628        509,748
           NASIDX            38          18,940         17,993

In [51]:
dec_24_orig_df['Entry_Date'].unique()

array([datetime.date(2024, 12, 2), datetime.date(2024, 11, 6),
       datetime.date(2024, 11, 25), datetime.date(2024, 11, 15),
       datetime.date(2024, 11, 18), datetime.date(2024, 11, 12),
       datetime.date(2024, 11, 5), datetime.date(2024, 11, 4),
       datetime.date(2024, 11, 19), datetime.date(2024, 11, 8),
       datetime.date(2024, 11, 14), datetime.date(2024, 11, 26),
       datetime.date(2024, 11, 20), datetime.date(2024, 11, 13),
       datetime.date(2024, 11, 11), datetime.date(2024, 11, 27),
       datetime.date(2024, 11, 21), datetime.date(2024, 11, 22),
       datetime.date(2024, 11, 7)], dtype=object)

In [57]:
dec_24_orig_df[dec_24_orig_df['Entry_Date']!=date(2024,12,2)].to_clipboard()

In [58]:
nov_24_true_df[nov_24_true_df['Entry_Date']==date(2024,11, 1)].to_clipboard()

In [87]:
oct_24_true_df[oct_24_true_df['PolicyNum']=='UE000260']

,CompID,PolicyNum,Plan,Product_Detail,Product,IssueDate,Indicator,Tranx,Dept_Desk,HedgeDate,Entry_Date,AsOf_Date,Cap,Strike,Base_Liab_Ntnl,Adj_Liab_Ntnl
123,1,UE000260,1U145800,IUL14B,IUL14B,2016-11-01,INDEX,EXCHNGE TO,IFRIX,2024-10-01,2024-10-01,2024-10-01,0.07,1.00,"5,104.25","4,849.04"

In [88]:
nov_24_orig_df[nov_24_orig_df['PolicyNum']=='UE000260']

,CompID,PolicyNum,Plan,Product_Detail,Product,IssueDate,Indicator,Tranx,Dept_Desk,HedgeDate,Entry_Date,AsOf_Date,Cap,Strike,Base_Liab_Ntnl,Adj_Liab_Ntnl
126,1,UE000260,1U145800,IUL14B,IUL14B,2016-11-01,INDEX,EXCHNGE TO,IFRIX,2024-11-01,2024-11-01,2024-11-01,0.07,1.00,"3,700.56","3,515.53"

In [89]:
nov_24_true_df[nov_24_true_df['PolicyNum']=='UE000260']

,CompID,PolicyNum,Plan,Product_Detail,Product,IssueDate,Indicator,Tranx,Dept_Desk,HedgeDate,Entry_Date,AsOf_Date,Cap,Strike,Base_Liab_Ntnl,Adj_Liab_Ntnl
127,1,UE000260,1U145800,IUL14B,IUL14B,2016-11-01,INDEX,EXCHNGE TO,IFRIX,2024-11-01,2024-11-01,2024-11-01,0.07,1.00,"3,700.56","3,515.53"

In [90]:
dec_24_orig_df[dec_24_orig_df['PolicyNum']=='UE000260']

,CompID,PolicyNum,Plan,Product_Detail,Product,IssueDate,Indicator,Tranx,Dept_Desk,HedgeDate,Entry_Date,AsOf_Date,Cap,Strike,Base_Liab_Ntnl,Adj_Liab_Ntnl
120,1,UE000260,1U145800,IUL14B,IUL14B,2016-11-01,INDEX,EXCHNGE TO,SWEEP,2024-12-02,2024-11-25,2024-09-01,0.07,1.00,"2,608.76","2,478.32"
121,1,UE000260,1U145800,IUL14B,IUL14B,2016-11-01,INDEX,EXCHNGE TO,IFRIX,2024-12-02,2024-11-25,2024-09-01,0.07,1.00,"34,238.57","32,526.64"
122,1,UE000260,1U145800,IUL14B,IUL14B,2016-11-01,INDEX,EXCHNGE TO,SWEEP,2024-12-02,2024-11-25,2024-10-01,0.07,1.00,701.30,666.23
123,1,UE000260,1U145800,IUL14B,IUL14B,2016-11-01,INDEX,EXCHNGE TO,IFRIX,2024-12-02,2024-11-25,2024-10-01,0.07,1.00,"5,338.09","5,071.19"
124,1,UE000260,1U145800,IUL14B,IUL14B,2016-11-01,INDEX,EXCHNGE TO,IFRIX,2024-12-02,2024-11-25,2024-11-01,0.07,1.00,"3,695.38","3,510.61"
125,1,UE000260,1U145800,IUL14B,IUL14B,2016-11-01,INDEX,EXCHNGE TO,IFRIX,2024-12-02,2024-12-02,2024-12-01,0.07,1.00,"5,228.05","4,966.65"

In [94]:
dec_24_true_df[dec_24_true_df['PolicyNum']=='UE000260']

,CompID,PolicyNum,Plan,Product_Detail,Product,IssueDate,Indicator,Tranx,Dept_Desk,HedgeDate,Entry_Date,AsOf_Date,Cap,Strike,Base_Liab_Ntnl,Adj_Liab_Ntnl
126,1,UE000260,1U145800,IUL14B,IUL14B,2016-11-01,INDEX,EXCHNGE TO,SWEEP,2024-12-02,2024-11-25,2024-09-01,0.07,1.00,"2,608.76","2,478.32"
127,1,UE000260,1U145800,IUL14B,IUL14B,2016-11-01,INDEX,EXCHNGE TO,IFRIX,2024-12-02,2024-11-25,2024-09-01,0.07,1.00,"34,238.57","32,526.64"
128,1,UE000260,1U145800,IUL14B,IUL14B,2016-11-01,INDEX,EXCHNGE TO,SWEEP,2024-12-02,2024-11-25,2024-10-01,0.07,1.00,701.30,666.23
129,1,UE000260,1U145800,IUL14B,IUL14B,2016-11-01,INDEX,EXCHNGE TO,IFRIX,2024-12-02,2024-11-25,2024-10-01,0.07,1.00,"5,338.09","5,071.19"
130,1,UE000260,1U145800,IUL14B,IUL14B,2016-11-01,INDEX,EXCHNGE TO,IFRIX,2024-12-02,2024-11-25,2024-11-01,0.07,1.00,"3,695.38","3,510.61"
131,1,UE000260,1U145800,IUL14B,IUL14B,2016-11-01,INDEX,EXCHNGE TO,IFRIX,2024-12-02,2024-12-02,2024-12-01,0.07,1.00,"5,228.05","4,966.65"

In [95]:
dec_24_true_df[dec_24_true_df['PolicyNum']=='UE000260'].to_clipboard()

In [62]:
nov_24_hedges_in_dec_24_inf_file = r'C:\Users\S0053071\Repos\Orion_Process_Backup\Nov_24_Hedges_In_Dec_24_Inforce.csv'
dec_24_inf = pd.read_csv(nov_24_hedges_in_dec_24_inf_file)

In [76]:
dec_24_inf[dec_24_inf['PolicyNum']=='UE000260']

,CompID,PolicyNum,Plan,Product_Detail,Product,Indicator,HedgeDate,Cap,Strike,Base_Liab_Ntnl,Adj_Liab_Ntnl
76,1,UE000260,1U145800,IUL14B,IUL14B,INDEX,2024-11-01,0,1,"4,635","4,404"
77,1,UE000260,1U145800,IUL14B,IUL14B,INDEX,2024-11-01,0,1,"4,635","4,404"

In [71]:
nov_24_true_df['AsOf_Date'].unique()

array([datetime.date(2024, 11, 1), datetime.date(2024, 10, 1),
       datetime.date(2024, 9, 1), datetime.date(2024, 5, 1),
       datetime.date(2024, 6, 1), datetime.date(2024, 7, 1),
       datetime.date(2024, 8, 1), datetime.date(2023, 8, 1),
       datetime.date(2023, 9, 1), datetime.date(2024, 1, 1),
       datetime.date(2024, 2, 1), datetime.date(2024, 3, 1),
       datetime.date(2024, 4, 1)], dtype=object)

In [75]:
dec_24_inf.columns

# desired_cols = ['CompID', 'PolicyNum', 'Plan', 'Product_Detail', 'Product', 'IssueDate', 'Indicator', 'Tranx', 'Dept_Desk', 'HedgeDate', 'Entry_Date', 'AsOf_Date', 'Cap', 'Strike', 'Base_Liab_Ntnl', 'Adj_Liab_Ntnl']
inf_desired_cols = ['CompID', 'PolicyNum', 'Plan', 'Product_Detail', 'Product', 'Indicator', 'HedgeDate', 'Cap',  'Strike', 'Base_Liab_Ntnl', 'Adj_Liab_Ntnl']
dec_24_inf = dec_24_inf[inf_desired_cols]

In [79]:
nov_24_orig_df.groupby('AsOf_Date').agg({'PolicyNum': 'count', 'Base_Liab_Ntnl':'sum', 'Adj_Liab_Ntnl':'sum'})

            PolicyNum  Base_Liab_Ntnl  Adj_Liab_Ntnl
AsOf_Date
2023-08-01          1              12             18
2023-09-01          1              27             40
2024-01-01          2             648            615
2024-02-01          2             650            617
2024-03-01          2             658            625
2024-04-01          2             670            637
2024-05-01         16          16,403         15,583
2024-06-01         19          13,915         13,219
2024-07-01         27          30,817         29,276
2024-08-01        154         103,506        131,868
2024-09-01        336         179,649        191,263
2024-10-01       2137       2,563,987      2,996,499
2024-11-01     171059      69,334,954     70,455,851

In [80]:
nov_24_true_df.groupby('AsOf_Date').agg({'PolicyNum': 'count', 'Base_Liab_Ntnl':'sum', 'Adj_Liab_Ntnl':'sum'})

            PolicyNum  Base_Liab_Ntnl  Adj_Liab_Ntnl
AsOf_Date
2023-08-01          1              12             18
2023-09-01          1              27             40
2024-01-01          2             648            615
2024-02-01          2             650            617
2024-03-01          2             658            625
2024-04-01          2             670            637
2024-05-01         16          16,403         15,583
2024-06-01         19          13,915         13,219
2024-07-01         27          30,817         29,276
2024-08-01        154         103,506        131,868
2024-09-01        337         179,695        191,367
2024-10-01       2198       2,581,428      3,014,292
2024-11-01     178148      70,263,856     71,450,773

In [78]:
dec_24_orig_df.groupby('AsOf_Date').agg({'PolicyNum': 'count', 'Base_Liab_Ntnl':'sum', 'Adj_Liab_Ntnl':'sum'})

            PolicyNum  Base_Liab_Ntnl  Adj_Liab_Ntnl
AsOf_Date
2024-06-01         14           2,348          2,230
2024-07-01         16           3,497          3,322
2024-08-01         21           4,195          4,374
2024-09-01         75         111,730        107,420
2024-10-01        184         112,275        108,612
2024-11-01       1678       1,374,456      1,658,801
2024-12-01     162078      66,022,466     67,271,159

In [1]:
dec_24_true_df.groupby('AsOf_Date').agg({'PolicyNum': 'count', 'Base_Liab_Ntnl':'sum', 'Adj_Liab_Ntnl':'sum'})

NameError: name 'dec_24_true_df' is not defined

In [77]:
dec_24_orig_df.groupby(['AsOf_Date', 'Indicator']).agg({'PolicyNum': 'count', 'Base_Liab_Ntnl':'sum', 'Adj_Liab_Ntnl':'sum'})

                      PolicyNum  Base_Liab_Ntnl  Adj_Liab_Ntnl
AsOf_Date  Indicator
2024-06-01 INDEX              6           1,228          1,166
           INX150             2              53             50
           INXFEE             4           1,014            963
           INXSPC             2              53             51
2024-07-01 INDEX              8           2,344          2,227
           INX150             2              53             51
           INXFEE             4           1,047            994
           INXSPC             2              53             51
2024-08-01 INDEX              9           2,515          2,389
           INX150             2              54             51
           INXFEE             4             979            930
           INXHIM             2             527            802
           INXSPC             2              54             51
           MARPRT             2              66            151
2024-09-01 INDEX             57         108,477        103,053
           INX150             2              55             53
           INXFEE             5           1,213          1,153
           INXHIM             6           1,696          2,577
           INXSPC             2              55             52
           MARPRT             3             233            532
2024-10-01 INDEX            155         107,569        102,167
           INX150             2              58             55
           INXFEE             9           2,074          1,971
           INXHIM             6           1,693          2,573
           INXSPC             2              58             55
           MARPRT             9             805          1,774
           NASIDX             1              17             16
2024-11-01 INDEX           1233         910,286        863,147
           INX150            44          17,848         16,956
           INXFEE           216          99,888         94,841
           INXHIM            49         102,217        155,370
           INXLOM            21           2,577          3,036
           INXSPC             5             193            183
           MARPRT            73         222,523        507,291
           NASIDX            37          18,923         17,977
2024-12-01 INDEX          92426      41,993,245     39,798,793
           INX150          5152       7,551,162      7,163,033
           INXFEE         36042       9,588,398      9,095,272
           INXHIM         10029       2,624,455      3,989,171
           INXLOM          4176         629,501        741,552
           INXSPC          2079         311,992        294,805
           MARPRT          7788       2,283,973      5,200,781
           NASIDX          4386       1,039,739        987,752