In [1]:
from xlsxwriter.utility import xl_rowcol_to_cell
from datetime import datetime, date
from pandas import DataFrame as df
from pathlib import Path
import pandas as pd
from os import path
# import datetime
import time
import os

pd.options.display.float_format = "{:,.2f}".format

from mthly_inforce_file import InforceFile
from mthly_hedge_file import HedgeFile

%load_ext autoreload
%autoreload 2

In [2]:
inforce_fldr = r'C:\Users\S0053071\Repos\Orion_Process_Backup\Inforce_Archive'
hdg_fldr = r'C:\Users\S0053071\Repos\Orion_Process_Backup\HdgRpts_Archive'

In [3]:
# for file_name in os.listdir(hdg_fldr):
#     print(file_name)
datetime.now().date()

datetime.date(2025, 1, 24)

In [44]:
def process_subdir_hdgfiles(target_dir, files_to_process=None):
    """
    Iterates over the subdirectories of a given directory and prints their paths.

    Args:
        target_dir: The path to the directory to iterate over.
    """
    
    final_cols = ['HedgeFile_Dt', 'Attrib_Type', 'HedgeDt', 'CompID', 'Indicator', 'Bbg_Idx', 'Fund_Name', 'Opt_Type', 'Strike', 'Cap/Rate', 'Budget', 'PolicyCount', 'Base_Liab_Ntnl', 'Notional']
    df_cols = ['HedgeDt', 'CompID', 'Indicator', 'Bbg_Idx', 'Fund_Name', 'Opt_Type', 'Strike', 'Cap/Rate', 'Budget', 'PolicyCount', 'Base_Liab_Ntnl', 'Notional']


    # orig_file = 'iul_liab_summary.csv'
    # true_file = 'iul_liab_summary_TRUE_UP.csv'
    hf_dict = {}
    
    target_dir = Path(target_dir)

    if files_to_process is None:
        # Set directories to all the valid directories
        # directories_to_process = [x[1] for x  in os.walk(target_dir)]
        # directories_to_process = directories_to_process[0]
        files_to_process = [f.name for f in target_dir.iterdir() if f.is_file()]
    
    for dirpath, _, filenames in os.walk(target_dir):
        
        for fname in filenames:

            if fname in files_to_process:

                hf_path = os.path.join(dirpath, fname)
                hdg_file = HedgeFile(hf_path)
                # hdg_file.import_mthly_hedge_txtfile()
                # hdg_file.create_summaries()
                hf_dict[(hdg_file.hedge_date, hdg_file.is_true_up)] = hdg_file
                    
    return hf_dict

In [45]:
file_filter = ['11_2024_HEDGE_ORIG.txt', '11_2024_HEDGE_TRUE_UP.txt', '10_2024_HEDGE_ORIG.txt', '10_2024_HEDGE_TRUE_UP.txt']

file_filter = ['10_2024_HEDGE_TRUE_UP.txt']

hf_dict = process_subdir_hdgfiles(hdg_fldr, file_filter)

Reading in Helper Dataframes (used for static lookups to obtain values for related fields)
REMINDER TO UPDATE NEW BUDGET INFO in Static_Assumptions Folder for ProductDetailsByHedgeDate.csv!!!
Reading Data from \\rgare.net\stlfinmkts\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\HedgeDates.csv
Reading Data from \\rgare.net\stlfinmkts\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\HdgFctrLU.csv
Reading Data from \\rgare.net\stlfinmkts\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\CoPlanInd_to_Prod.csv
Reading Data from \\rgare.net\stlfinmkts\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\Indicator_to_FundName.csv
Reading Data from \\rgare.net\stlfinmkts\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\ProductDetailsByHedgeDate.csv
Reading Data from \\rgare.net\stlfinmkts\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\Static_Assumptions\Orion_IUL_Policies.csv
Converting Static Assum DataFrame Dates to Datetime.Date
Attempting to extract date from hedge file since date parameter was not provided
Hedge Date set to 2024-10-01
Based on the hedge file name, this is a true-up file
Hedge File Path provided as a non-directory for new hedges on 2024-10-01
Hedge File Path set to: C:\Users\S0053071\Repos\Orion_Process_Backup\HdgRpts_Archive\10_2024_HEDGE_TRUE_UP.txt
Hedge TrueUp is set to True

In [46]:
oct_true_up = hf_dict[list(hf_dict.keys())[0]]

In [47]:
oct_true_up.import_mthly_hedge_txtfile()

Importing Hedge Txt File

\\rgare.net\stlfinmkts\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\1_Code\mthly_hedge_file.py:314: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  hedgefile_df = pd.read_csv(self.hedge_file, index_col=False, header=None, names=hedgefile_colnames, skipfooter=2, engine='python', low_memory=True)

Time Reading Hedge File: 0 mins 4 secs

,CompID,PolicyNum,Plan,IssueDate,Indicator,Tranx,Rev,Dept_Desk,Entry_Date,AsOf_Date,Base_Liab_Ntnl,Part,Cap,MGIR_(Cap),Floor,Spec_Rate,Spread,Asset_Charge,Multiplier,Status
0,1,UE000006,1U145500,2016-06-23,INX150,EXCESS INT,,INDEX,2024-10-01,2024-10-01,19.40,1.00,0.09,3.00,0.01,0.00,0.00,0.00,0.00,R
1,1,UE000006,1U145500,2016-06-23,INXFEE,EXCESS INT,,INDEX,2024-10-01,2024-10-01,63.18,1.00,10.00,999.99,0.00,0.00,0.08,0.00,0.00,R
2,1,UE000006,1U145500,2016-06-23,INX150,EXCHNGE TO,,SWEEP,2024-10-01,2024-10-01,24.91,1.00,0.09,3.00,0.01,0.00,0.00,0.00,0.00,R
3,1,UE000006,1U145500,2016-06-23,INXFEE,EXCHNGE TO,,SWEEP,2024-10-01,2024-10-01,24.92,1.00,10.00,999.99,0.00,0.00,0.08,0.00,0.00,R
4,1,UE000006,1U145500,2016-06-23,INX150,EXCHNGE FROM,,IFRIC,2024-10-01,2024-10-01,247.69,1.00,0.09,3.00,0.01,0.00,0.00,0.00,0.00,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
376901,26,UN011777,1U146900,2023-04-14,INDEX,EXCHNGE TO,,IFRIX,2024-10-01,2024-10-01,83.70,1.00,0.09,3.00,0.00,0.00,0.00,0.00,0.00,R
376902,26,UN011856,1U146900,2023-09-06,INDEX,EXCHNGE TO,,SWEEP,2024-10-01,2024-10-01,351.77,1.00,0.09,3.00,0.00,0.00,0.00,0.00,0.00,R
376903,26,UN011856,1U146900,2023-09-06,INXFEE,EXCHNGE TO,,SWEEP,2024-10-01,2024-10-01,351.78,1.00,10.00,999.99,0.00,0.00,0.08,0.00,0.00,R
376904,26,UN012447,1U146900,2024-01-20,INDEX,EXCHNGE TO,,SWEEP,2024-10-01,2024-10-01,403.63,1.00,0.09,3.00,0.00,0.00,0.00,0.00,0.00,R
376905,26,UN012998,1U146900,2023-10-26,INDEX,EXCHNGE TO,,SWEEP,2024-10-01,2024-10-01,160.16,1.00,0.09,3.00,0.00,0.00,0.00,0.00,0.00,R

In [26]:
oct_true_up.first_bd

datetime.date(2024, 10, 1)

In [49]:
oct_true_up.create_idx_credit_df()

Starting Creation of Index Crediting Summaries
Merging Hedge File w/ Helper Files to Add Additional Fields
Finished...Time Merging Hedge File: 0 mins 0 secs
The prior year cohort was effective from 2023-09-29 and matures on 2024-10-01, and the 1st BD of this month is 2024-10-01
Grabbing Mkt Price Dict on 2023-09-29
Prices on Prior Cohort Effective Date: {'MXEA Index': 2031.26, 'RTY Index': 1785.102, 'NDX Index': 14715.24, 'SPX Index': 4288.05, 'SPMARC5P Index': 347.34}
Grabbing Mkt Price Dict on 2024-10-01
Prices for Prior Cohort Maturity, based on 2024-10-01: {'MXEA Index': 2454.84, 'RTY Index': 2197.032, 'NDX Index': 19773.3, 'SPX Index': 5708.75, 'SPMARC5P Index': 390.52}

,HedgeDt,Seg_StartDt,Seg_EndDt,IdxLvl_EndDt_DateUsed,CompID,PolicyNum,IssueDate,Plan,Indicator,Tranx,...,Strike,Cap,Idx_Credit_Amt,IdxLvl_StartDt,IdxLvl_EndDt,Strike_Low,Strike_High,Idx_Rtn,Payoff_PctRtn,Implied_Ntnl
0,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,UE000006,2016-06-23,1U145500,INX150,EXCESS INT,...,1.01,0.09,19.40,"4,288.05","5,708.75","4,352.37","4,652.53",0.33,0.07,277.14
1,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,UE000006,2016-06-23,1U145500,INXFEE,EXCESS INT,...,1.08,10.00,63.18,"4,288.05","5,708.75","4,631.09",,0.33,0.25,251.40
2,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,UE000011,2016-05-09,1U145500,INX150,EXCESS INT,...,1.01,0.09,20.79,"4,288.05","5,708.75","4,352.37","4,652.53",0.33,0.07,297.00
3,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,UE000012,2016-05-09,1U145500,INX150,EXCESS INT,...,1.01,0.09,19.78,"4,288.05","5,708.75","4,352.37","4,652.53",0.33,0.07,282.57
4,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,UE000013,2016-05-20,1U145500,INX150,EXCESS INT,...,1.01,0.09,5.23,"4,288.05","5,708.75","4,352.37","4,652.53",0.33,0.07,74.71
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88959,2023-10-01,2023-09-29,2024-10-01,2024-10-01,26,UN011372,2022-11-03,1U146900,INDEX,EXCESS INT,...,1.00,0.09,5.94,"4,288.05","5,708.75","4,288.05","4,652.53",0.33,0.08,69.88
88960,2023-10-01,2023-09-29,2024-10-01,2024-10-01,26,UN011372,2022-11-03,1U146900,INXFEE,EXCESS INT,...,1.08,10.00,17.75,"4,288.05","5,708.75","4,620.37",,0.33,0.25,69.93
88961,2023-10-01,2023-09-29,2024-10-01,2024-10-01,26,UN011420,2022-09-06,1U146900,INDEX,EXCESS INT,...,1.00,0.09,1.57,"4,288.05","5,708.75","4,288.05","4,652.53",0.33,0.08,18.47
88962,2023-10-01,2023-09-29,2024-10-01,2024-10-01,26,UN011420,2022-09-06,1U146900,INX150,EXCESS INT,...,1.01,0.07,1.29,"4,288.05","5,708.75","4,352.37","4,588.21",0.33,0.06,23.45
88963,2023-10-01,2023-09-29,2024-10-01,2024-10-01,26,UN011777,2023-04-14,1U146900,INDEX,EXCESS INT,...,1.00,0.09,6.56,"4,288.05","5,708.75","4,288.05","4,652.53",0.33,0.08,77.18

In [35]:
oct_true_up.idx_credit_df.columns

Index(['HedgeDt', 'Seg_StartDt', 'Seg_EndDt', 'IdxLvl_EndDt_DateUsed',
       'CompID', 'PolicyNum', 'IssueDate', 'Plan', 'Indicator', 'Tranx',
       'Dept_Desk', 'Entry_Date', 'Product_Detail', 'Ntnl_Mult', 'Coins',
       'HedgeRatio', 'HdgFctr', 'Budget', 'Bbg_Idx', 'Fund_Name', 'Opt_Type',
       'Strike', 'Cap', 'Idx_Credit_Amt', 'IdxLvl_StartDt', 'IdxLvl_EndDt'],
      dtype='object')

In [58]:
oct_true_up.idx_credit_df.to_clipboard(index=False)

In [51]:
oct_true_up.add_orion_status_flag(oct_true_up.idx_credit_df)

,HedgeDt,Seg_StartDt,Seg_EndDt,IdxLvl_EndDt_DateUsed,CompID,PolicyNum,IssueDate,Plan,Indicator,Tranx,...,Cap,Idx_Credit_Amt,IdxLvl_StartDt,IdxLvl_EndDt,Strike_Low,Strike_High,Idx_Rtn,Payoff_PctRtn,Implied_Ntnl,Status
0,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,UE000006,2016-06-23,1U145500,INX150,EXCESS INT,...,0.09,19.40,"4,288.05","5,708.75","4,352.37","4,652.53",0.33,0.07,277.14,R
1,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,UE000006,2016-06-23,1U145500,INXFEE,EXCESS INT,...,10.00,63.18,"4,288.05","5,708.75","4,631.09",,0.33,0.25,251.40,R
2,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,UE000011,2016-05-09,1U145500,INX150,EXCESS INT,...,0.09,20.79,"4,288.05","5,708.75","4,352.37","4,652.53",0.33,0.07,297.00,R
3,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,UE000012,2016-05-09,1U145500,INX150,EXCESS INT,...,0.09,19.78,"4,288.05","5,708.75","4,352.37","4,652.53",0.33,0.07,282.57,R
4,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,UE000013,2016-05-20,1U145500,INX150,EXCESS INT,...,0.09,5.23,"4,288.05","5,708.75","4,352.37","4,652.53",0.33,0.07,74.71,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88959,2023-10-01,2023-09-29,2024-10-01,2024-10-01,26,UN011372,2022-11-03,1U146900,INDEX,EXCESS INT,...,0.09,5.94,"4,288.05","5,708.75","4,288.05","4,652.53",0.33,0.08,69.88,R
88960,2023-10-01,2023-09-29,2024-10-01,2024-10-01,26,UN011372,2022-11-03,1U146900,INXFEE,EXCESS INT,...,10.00,17.75,"4,288.05","5,708.75","4,620.37",,0.33,0.25,69.93,R
88961,2023-10-01,2023-09-29,2024-10-01,2024-10-01,26,UN011420,2022-09-06,1U146900,INDEX,EXCESS INT,...,0.09,1.57,"4,288.05","5,708.75","4,288.05","4,652.53",0.33,0.08,18.47,R
88962,2023-10-01,2023-09-29,2024-10-01,2024-10-01,26,UN011420,2022-09-06,1U146900,INX150,EXCESS INT,...,0.07,1.29,"4,288.05","5,708.75","4,352.37","4,588.21",0.33,0.06,23.45,R
88963,2023-10-01,2023-09-29,2024-10-01,2024-10-01,26,UN011777,2023-04-14,1U146900,INDEX,EXCESS INT,...,0.09,6.56,"4,288.05","5,708.75","4,288.05","4,652.53",0.33,0.08,77.18,R

In [65]:
group_by_cols = ['Status', 'HedgeDt', 'Seg_StartDt', 'Seg_EndDt', 'IdxLvl_EndDt_DateUsed', 'CompID', 'Fund_Name']
# idx_credit_df_summary = (oct_true_up.remove_non_orion(oct_true_up.idx_credit_df.copy(deep=True))).groupby(group_by_cols, as_index=False).agg({'PolicyNum':'count', 'Idx_Credit_Amt':'sum', 'Implied_Ntnl':'sum'})
idx_credit_df_summary = oct_true_up.idx_credit_df.groupby(group_by_cols, as_index=False).agg({'PolicyNum':'count', 'Idx_Credit_Amt':'sum', 'Implied_Ntnl':'sum'})
idx_credit_df_summary.rename(columns={'PolicyNum': 'PolicyCount'}, inplace=True)

In [66]:
idx_credit_df_summary #.to_clipboard()

,Status,HedgeDt,Seg_StartDt,Seg_EndDt,IdxLvl_EndDt_DateUsed,CompID,Fund_Name,PolicyCount,Idx_Credit_Amt,Implied_Ntnl
0,N,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,NASDAQ-100 1 Yr Pt-to-Pt 100 Part w Cap,40,226.34,"2,211.64"
1,N,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,S&P 500 1 Yr Pt-to-Pt 100 Part w Cap,613,"23,355.40","238,391.26"
2,N,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,S&P 500 1 Yr Pt-to-Pt 100 Part w Cap & Floor,12,536.26,"7,660.86"
3,N,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,S&P 500 1 Yr Pt-to-Pt Multiplier w Cap,7,24.75,206.25
4,N,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,S&P 500 1 Yr Pt-to-Pt Uncapped w Fee,88,"2,628.79","10,460.09"
5,N,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,S&P 500 1 Yr Specified Rate,6,8.42,112.27
6,N,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,S&P MARC 5% 1 Yr Pt-to-Pt Uncapped,30,268.35,"2,158.61"
7,R,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,NASDAQ-100 1 Yr Pt-to-Pt 100 Part w Cap,1960,"29,494.68","289,800.55"
8,R,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,S&P 500 1 Yr Pt-to-Pt 100 Part w Cap,49839,"3,865,217.22","39,597,843.81"
9,R,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,S&P 500 1 Yr Pt-to-Pt 100 Part w Cap & Floor,2805,"103,995.60","1,501,855.32"
10,R,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,S&P 500 1 Yr Pt-to-Pt Multiplier w Cap,7753,"487,688.18","4,064,068.17"
11,R,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,S&P 500 1 Yr Pt-to-Pt Uncapped w Fee,20065,"2,130,389.07","8,484,455.70"
12,R,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,S&P 500 1 Yr Specified Rate,1152,"38,218.58","525,263.37"
13,R,2023-10-01,2023-09-29,2024-10-01,2024-10-01,1,S&P MARC 5% 1 Yr Pt-to-Pt Uncapped,3124,"268,643.20","2,160,966.40"
14,R,2023-10-01,2023-09-29,2024-10-01,2024-10-01,26,S&P 500 1 Yr Pt-to-Pt 100 Part w Cap,998,"117,827.13","1,386,856.54"
15,R,2023-10-01,2023-09-29,2024-10-01,2024-10-01,26,S&P 500 1 Yr Pt-to-Pt 100 Part w Cap & Floor,215,"3,480.74","63,915.17"
16,R,2023-10-01,2023-09-29,2024-10-01,2024-10-01,26,S&P 500 1 Yr Pt-to-Pt Uncapped w Fee,193,"16,819.49","66,332.74"
17,R,2023-10-01,2023-09-29,2024-10-01,2024-10-01,26,S&P 500 1 Yr Specified Rate,64,826.80,"12,991.61"

In [53]:
oct_true_up.idx_credit_df['Status'].unique()

array(['R', 'N'], dtype=object)

In [57]:
oct_true_up.idx_credit_df.groupby(['CompID', 'Fund_Name']).agg({'Idx_Credit_Amt':'sum'}).to_clipboard()

In [7]:
print(list(hf_dict.keys())[0])
# oct_orig = hf_dict[list(hf_dict.keys())[0]].idx_credit_df
oct_true_credit_df = hf_dict[list(hf_dict.keys())[0]].idx_credit_df

(datetime.date(2024, 10, 1), True)

In [8]:
hf_dict[list(hf_dict.keys())[0]].hedgefile_df

,CompID,PolicyNum,Plan,IssueDate,Indicator,Tranx,Rev,Dept_Desk,Entry_Date,AsOf_Date,Base_Liab_Ntnl,Part,Cap,MGIR_(Cap),Floor,Spec_Rate,Spread,Asset_Charge,Multiplier,Status
0,1,UE000006,1U145500,2016-06-23,INX150,EXCESS INT,,INDEX,2024-10-01,2024-10-01,19.40,1.00,0.09,3.00,0.01,0.00,0.00,0.00,0.00,R
1,1,UE000006,1U145500,2016-06-23,INXFEE,EXCESS INT,,INDEX,2024-10-01,2024-10-01,63.18,1.00,10.00,999.99,0.00,0.00,0.08,0.00,0.00,R
2,1,UE000006,1U145500,2016-06-23,INX150,EXCHNGE TO,,SWEEP,2024-10-01,2024-10-01,24.91,1.00,0.09,3.00,0.01,0.00,0.00,0.00,0.00,R
3,1,UE000006,1U145500,2016-06-23,INXFEE,EXCHNGE TO,,SWEEP,2024-10-01,2024-10-01,24.92,1.00,10.00,999.99,0.00,0.00,0.08,0.00,0.00,R
4,1,UE000006,1U145500,2016-06-23,INX150,EXCHNGE FROM,,IFRIC,2024-10-01,2024-10-01,247.69,1.00,0.09,3.00,0.01,0.00,0.00,0.00,0.00,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
376901,26,UN011777,1U146900,2023-04-14,INDEX,EXCHNGE TO,,IFRIX,2024-10-01,2024-10-01,83.70,1.00,0.09,3.00,0.00,0.00,0.00,0.00,0.00,R
376902,26,UN011856,1U146900,2023-09-06,INDEX,EXCHNGE TO,,SWEEP,2024-10-01,2024-10-01,351.77,1.00,0.09,3.00,0.00,0.00,0.00,0.00,0.00,R
376903,26,UN011856,1U146900,2023-09-06,INXFEE,EXCHNGE TO,,SWEEP,2024-10-01,2024-10-01,351.78,1.00,10.00,999.99,0.00,0.00,0.08,0.00,0.00,R
376904,26,UN012447,1U146900,2024-01-20,INDEX,EXCHNGE TO,,SWEEP,2024-10-01,2024-10-01,403.63,1.00,0.09,3.00,0.00,0.00,0.00,0.00,0.00,R
376905,26,UN012998,1U146900,2023-10-26,INDEX,EXCHNGE TO,,SWEEP,2024-10-01,2024-10-01,160.16,1.00,0.09,3.00,0.00,0.00,0.00,0.00,0.00,R

In [10]:
hf_dict[list(hf_dict.keys())[0]].inforce_summary_df

,HedgeDt,CompID,PolicyNum,IssueDate,Plan,Indicator,Cap,Strike,Budget,Ntnl_Mult,Base_Liab_Ntnl,Adj_Liab_Ntnl,HedgeRatio,Target_Liab_Ntnl
0,2024-04-01,1,U0660314,2015-04-22,1U145500,INDEX,0.10,1.00,0.05,1.00,"12,277.21","12,277.21",0.97,"11,908.89"
1,2024-04-01,1,UE134285,2021-06-20,1U146800,INDEX,0.10,1.00,0.05,1.00,92.37,92.37,0.97,89.60
2,2024-04-01,1,UE184692,2022-03-15,1U147500,INDEX,0.10,1.00,0.05,1.00,26.21,26.21,0.97,25.42
3,2024-04-01,1,UE184692,2022-03-15,1U147500,INXFEE,10.00,1.08,0.04,1.00,36.75,36.75,0.97,35.65
4,2024-04-01,1,UE184692,2022-03-15,1U147500,MARPRT,10.00,1.00,0.02,2.40,8.44,20.26,0.97,19.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101706,2024-10-01,26,UNS03006,2024-03-15,1U146900,INXSPC,0.07,1.00,0.05,1.00,78.38,62.70,0.95,59.57
101707,2024-10-01,26,UNS03009,2024-03-18,1U146900,INDEX,0.09,1.00,0.05,1.00,13.24,10.59,0.95,10.06
101708,2024-10-01,26,UNS03009,2024-03-18,1U146900,INX150,0.07,1.01,0.03,1.00,13.24,10.59,0.95,10.06
101709,2024-10-01,26,UNS03055,2024-05-28,1U146900,INDEX,0.09,1.00,0.05,1.00,65.66,52.53,0.95,49.90
101710,2024-10-01,26,UNS03055,2024-05-28,1U146900,INX150,0.07,1.01,0.03,1.00,65.66,52.53,0.95,49.90

In [18]:
hf_dict[list(hf_dict.keys())[0]].first_bd

AttributeError: 'HedgeFile' object has no attribute 'first_bd'

In [11]:
oct_true_credit_df.shape

(88964, 33)

In [ ]:
oct_true_credit_df

,CompID,PolicyNum,Plan,IssueDate,Indicator,Tranx,Rev,Dept_Desk,Entry_Date,AsOf_Date,...,Floor,Spec_Rate,Spread,Asset_Charge,Multiplier,Orion_Idx,Bbg_Idx,Fund_Name,Opt_Type,Opt_Term_Yrs
0,1,UE000006,1U145500,2016-06-23,INX150,EXCESS INT,,INDEX,2024-10-01,2023-10-01,...,0.01,0.00,0.00,0.00,0.00,S&P 500,SPX Index,S&P 500 1 Yr Pt-to-Pt 100 Part w Cap & Floor,Call Spread,1
1,1,UE000006,1U145500,2016-06-23,INXFEE,EXCESS INT,,INDEX,2024-10-01,2023-10-01,...,0.00,0.00,0.08,0.00,0.00,S&P 500,SPX Index,S&P 500 1 Yr Pt-to-Pt Uncapped w Fee,Call,1
2,1,UE000011,1U145500,2016-05-09,INX150,EXCESS INT,,INDEX,2024-10-01,2023-10-01,...,0.01,0.00,0.00,0.00,0.00,S&P 500,SPX Index,S&P 500 1 Yr Pt-to-Pt 100 Part w Cap & Floor,Call Spread,1
3,1,UE000012,1U145500,2016-05-09,INX150,EXCESS INT,,INDEX,2024-10-01,2023-10-01,...,0.01,0.00,0.00,0.00,0.00,S&P 500,SPX Index,S&P 500 1 Yr Pt-to-Pt 100 Part w Cap & Floor,Call Spread,1
4,1,UE000013,1U145500,2016-05-20,INX150,EXCESS INT,,INDEX,2024-10-01,2023-10-01,...,0.01,0.00,0.00,0.00,0.00,S&P 500,SPX Index,S&P 500 1 Yr Pt-to-Pt 100 Part w Cap & Floor,Call Spread,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88959,26,UN011372,1U146900,2022-11-03,INDEX,EXCESS INT,,INDEX,2024-10-01,2023-10-01,...,0.00,0.00,0.00,0.00,0.00,S&P 500,SPX Index,S&P 500 1 Yr Pt-to-Pt 100 Part w Cap,Call Spread,1
88960,26,UN011372,1U146900,2022-11-03,INXFEE,EXCESS INT,,INDEX,2024-10-01,2023-10-01,...,0.00,0.00,0.08,0.00,0.00,S&P 500,SPX Index,S&P 500 1 Yr Pt-to-Pt Uncapped w Fee,Call,1
88961,26,UN011420,1U146900,2022-09-06,INDEX,EXCESS INT,,INDEX,2024-10-01,2023-10-01,...,0.00,0.00,0.00,0.00,0.00,S&P 500,SPX Index,S&P 500 1 Yr Pt-to-Pt 100 Part w Cap,Call Spread,1
88962,26,UN011420,1U146900,2022-09-06,INX150,EXCESS INT,,INDEX,2024-10-01,2023-10-01,...,0.01,0.00,0.00,0.00,0.00,S&P 500,SPX Index,S&P 500 1 Yr Pt-to-Pt 100 Part w Cap & Floor,Call Spread,1
88963,26,UN011777,1U146900,2023-04-14,INDEX,EXCESS INT,,INDEX,2024-10-01,2023-10-01,...,0.00,0.00,0.00,0.00,0.00,S&P 500,SPX Index,S&P 500 1 Yr Pt-to-Pt 100 Part w Cap,Call Spread,1

In [17]:
# oct_true_credit_df[oct_true_credit_df['Idx_Credit_Amt'].isna()]
# oct_true_credit_df[oct_true_credit_df['Idx_Credit_Amt']==0]

# Get unique combinations of columns
# unique_combinations = oct_true_credit_df[['Entry_Date', 'HedgeDt', 'Seg_StartDt', 'Seg_EndDt']].drop_duplicates()
oct_true_credit_df[['Entry_Date', 'HedgeDt', 'Seg_StartDt', 'Seg_EndDt']].drop_duplicates()

   Entry_Date     HedgeDt Seg_StartDt   Seg_EndDt
0  2024-10-01  2023-10-01  2023-09-29  2024-10-01

In [21]:
list(oct_true_credit_df['Bbg_Idx'].unique())

['SPX Index', 'SPMARC5P Index', 'NDX Index']

In [13]:
oct_true_credit_df.columns

Index(['CompID', 'PolicyNum', 'Plan', 'IssueDate', 'Indicator', 'Tranx', 'Rev',
       'Dept_Desk', 'Entry_Date', 'AsOf_Date', 'Idx_Credit_Amt', 'HedgeDt',
       'FirstBD', 'Seg_StartDt', 'Seg_EndDt', 'Coins', 'HedgeRatio', 'HdgFctr',
       'Product_Detail', 'Product', 'Budget', 'Part', 'Cap', 'Floor',
       'Spec_Rate', 'Spread', 'Asset_Charge', 'Multiplier', 'Orion_Idx',
       'Bbg_Idx', 'Fund_Name', 'Opt_Type', 'Opt_Term_Yrs'],
      dtype='object')

In [14]:
oct_true_credit_df['Entry_Date'].unique()

array([datetime.date(2024, 10, 1)], dtype=object)

In [ ]:
"""
To replicate interest credited
Step 1:
    Create List of Surrendered Policies by filtering Hedge Report for Tranx ==  "Surrender" and removing duplicates
Step 2:
    Remove all transactions associated with Surrendered Policies from step 1
    This is likely why your True up interest numbers are higher than what is in the report when comparing the true up vs the pdf. 
Step 3:
     Filter for Tranx == 'Excess Int'
"""

In [8]:
# oct_true_credit_df = oct_true_credit_df[oct_true_credit_df['Status'].str.contains('R')]
len(oct_true_credit_df)

372807

In [27]:
surr_pols = oct_true_credit_df[oct_true_credit_df['Tranx']=='SURRENDER']['PolicyNum'].unique()
len(surr_pols)
# surr_pols_df = pd.DataFrame(surr_pols, columns=['PolicyNum'])

192

In [28]:
credit_df = oct_true_credit_df[oct_true_credit_df['Tranx']=='EXCESS INT']

In [34]:
len(credit_df)

89163

In [32]:
credit_df_no_surr = credit_df[~credit_df['PolicyNum'].isin(surr_pols)]

In [33]:
len(credit_df_no_surr)

88964

In [30]:
credit_df_no_surr = credit_df_no_surr[credit_df_no_surr['Rev'].str.contains(' ')]

In [31]:
len(credit_df_no_surr)

88964

In [35]:
hf_credit_summary = credit_df_no_surr.groupby(['AsOf_Date', 'CompID', 'Indicator'], as_index=False).agg({'PolicyNum':'count', 'Base_Liab_Ntnl': 'sum'})
cols_ordered = ['AsOf_Date', 'CompID', 'Indicator', 'PolicyNum', 'Base_Liab_Ntnl']
hf_credit_summary = hf_credit_summary[cols_ordered]
hf_credit_summary.rename(columns={'AsOf_Date': 'InforceDt', 'PolicyNum': 'PolicyCount', 'Base_Liab_Ntnl': 'Idx_Credit_Amt'}, inplace=True)

In [24]:
hf_credit_summary

     InforceDt  CompID Indicator  PolicyCount  Idx_Credit_Amt
0   2024-10-01       1     INDEX        49839    3,865,217.22
1   2024-10-01       1    INX150         2805      103,995.60
2   2024-10-01       1    INXFEE        20065    2,130,389.07
3   2024-10-01       1    INXHIM         5508      441,477.29
4   2024-10-01       1    INXLOM         2245       46,210.89
5   2024-10-01       1    INXSPC         1152       38,218.58
6   2024-10-01       1    MARPRT         3124      268,643.20
7   2024-10-01       1    NASIDX         1960       29,494.68
8   2024-10-01      26     INDEX          998      117,827.13
9   2024-10-01      26    INX150          215        3,480.74
10  2024-10-01      26    INXFEE          193       16,819.49
11  2024-10-01      26    INXSPC           64          826.80

In [36]:
hf_credit_summary.to_clipboard(index=False)

In [40]:
all_inxhim_credits = oct_true_credit_df[(oct_true_credit_df['Tranx']=='EXCESS INT') & (oct_true_credit_df['Indicator']=='INXHIM')]
cols = ['PolicyNum', 'Plan', 'Indicator', 'Tranx', 'Rev', 'Dept_Desk', 'Entry_Date', 'AsOf_Date', 'Base_Liab_Ntnl', 'Status']
all_inxhim_credits = all_inxhim_credits[cols]
all_inxhim_credits['Surrender'] = False
all_inxhim_credits.loc[all_inxhim_credits['PolicyNum'].isin(surr_pols), 'Surrender'] = True

In [42]:
all_inxhim_credits.to_clipboard(index=False)

In [25]:
# oct_orig_credit = oct_orig[oct_orig['Tranx']=='EXCESS INT']
# oct_orig_credit

oct_orig_credit = oct_orig[oct_orig['Dept_Desk']=='INDEX']
oct_orig_credit

,CompID,PolicyNum,Plan,IssueDate,Indicator,Tranx,Rev,Dept_Desk,Entry_Date,AsOf_Date,Base_Liab_Ntnl,Part,Cap,MGIR_(Cap),Floor,Spec_Rate,Spread,Asset_Charge,Multiplier,Status
0,1,UE000006,1U145500,2016-06-23,INX150,EXCESS INT,,INDEX,2024-10-01,2024-10-01,19.40,1.00,0.09,3.00,0.01,0.00,0.00,0.00,0.00,R
1,1,UE000006,1U145500,2016-06-23,INXFEE,EXCESS INT,,INDEX,2024-10-01,2024-10-01,66.33,1.00,10.00,999.99,0.00,0.00,0.08,0.00,0.00,R
8,1,UE000011,1U145500,2016-05-09,INX150,EXCESS INT,,INDEX,2024-10-01,2024-10-01,20.79,1.00,0.09,3.00,0.01,0.00,0.00,0.00,0.00,R
12,1,UE000012,1U145500,2016-05-09,INX150,EXCESS INT,,INDEX,2024-10-01,2024-10-01,19.78,1.00,0.09,3.00,0.01,0.00,0.00,0.00,0.00,R
16,1,UE000013,1U145500,2016-05-20,INX150,EXCESS INT,,INDEX,2024-10-01,2024-10-01,5.23,1.00,0.09,3.00,0.01,0.00,0.00,0.00,0.00,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372919,26,UN011372,1U146900,2022-11-03,INDEX,EXCESS INT,,INDEX,2024-10-01,2024-10-01,5.94,1.00,0.09,3.00,0.00,0.00,0.00,0.00,0.00,R
372920,26,UN011372,1U146900,2022-11-03,INXFEE,EXCESS INT,,INDEX,2024-10-01,2024-10-01,18.63,1.00,10.00,999.99,0.00,0.00,0.08,0.00,0.00,R
372930,26,UN011420,1U146900,2022-09-06,INDEX,EXCESS INT,,INDEX,2024-10-01,2024-10-01,1.57,1.00,0.09,3.00,0.00,0.00,0.00,0.00,0.00,R
372931,26,UN011420,1U146900,2022-09-06,INX150,EXCESS INT,,INDEX,2024-10-01,2024-10-01,1.29,1.00,0.07,3.00,0.01,0.00,0.00,0.00,0.00,R
372940,26,UN011777,1U146900,2023-04-14,INDEX,EXCESS INT,,INDEX,2024-10-01,2024-10-01,6.56,1.00,0.09,3.00,0.00,0.00,0.00,0.00,0.00,R

In [27]:
# oct_orig_credit['Dept_Desk'].unique()
# oct_orig_credit['Dept_Desk'].unique()
# oct_orig_credit['Tranx'].unique()
oct_orig_credit['Rev'].unique()

array([' '], dtype=object)

In [28]:
hf_credit_summary = None

for (hdg_dt, true_up), hf_obj in hf_dict.items():

    credit_df = hf_obj.idx_credit_df
    credit_df = credit_df[credit_df['Tranx']=='EXCESS INT']
    credit_df = credit_df[credit_df['Rev'].str.contains(' ')]

    # NOTE!  THIS NEEDS TO BE EXCLUDED IF USING HEDGE FILES BEFORE 10/1/2024
    # credit_df = credit_df[credit_df['Status'].str.contains('R')]


    # credit_df = credit_df.groupby('HedgeDate', as_index=False).agg({'PolicyNum':'count', 'Base_Liab_Ntnl': 'sum', 'Adj_Liab_Ntnl': 'sum'})

    # credit_df = credit_df.groupby(['AsOf_Date', 'Indicator', 'Rev'], as_index=False).agg({'PolicyNum':'count', 'Base_Liab_Ntnl': 'sum'})
    credit_df = credit_df.groupby(['AsOf_Date', 'CompID', 'Indicator'], as_index=False).agg({'PolicyNum':'count', 'Base_Liab_Ntnl': 'sum'})
    credit_df['HedgeFile_AsOfDt'] = hdg_dt
    credit_df['Source'] = 'TRUE_UP' if true_up else 'ORIG'

    if hf_credit_summary is None:
        hf_credit_summary = credit_df
    else:
        hf_credit_summary = pd.concat([hf_credit_summary, credit_df]).reset_index(drop=True)


# cols_ordered = ['HedgeFile_AsOfDt', 'AsOf_Date', 'Source', 'Rev', 'Indicator', 'PolicyNum', 'Base_Liab_Ntnl']
cols_ordered = ['HedgeFile_AsOfDt', 'AsOf_Date', 'Source', 'CompID', 'Indicator', 'PolicyNum', 'Base_Liab_Ntnl']
hf_credit_summary = hf_credit_summary[cols_ordered]
hf_credit_summary.rename(columns={'PolicyNum': 'PolicyCount', 'Base_Liab_Ntnl': 'Idx_Credit_Amt'}, inplace=True)

In [29]:
hf_credit_summary

,HedgeFile_AsOfDt,AsOf_Date,Source,CompID,Indicator,PolicyCount,Idx_Credit_Amt
0,2024-10-01,2024-10-01,ORIG,1,INDEX,50575,"4,101,161.66"
1,2024-10-01,2024-10-01,ORIG,1,INX150,2821,"104,667.19"
2,2024-10-01,2024-10-01,ORIG,1,INXFEE,20189,"2,250,875.75"
3,2024-10-01,2024-10-01,ORIG,1,INXHIM,5523,"442,971.77"
4,2024-10-01,2024-10-01,ORIG,1,INXLOM,2254,"46,345.46"
5,2024-10-01,2024-10-01,ORIG,1,INXSPC,1161,"38,344.78"
6,2024-10-01,2024-10-01,ORIG,1,MARPRT,3163,"263,684.55"
7,2024-10-01,2024-10-01,ORIG,1,NASIDX,2004,"29,811.76"
8,2024-10-01,2024-10-01,ORIG,26,INDEX,1001,"118,010.91"
9,2024-10-01,2024-10-01,ORIG,26,INX150,216,"3,518.04"
10,2024-10-01,2024-10-01,ORIG,26,INXFEE,193,"17,650.67"
11,2024-10-01,2024-10-01,ORIG,26,INXSPC,64,826.80
12,2024-10-01,2024-10-01,TRUE_UP,1,INDEX,50575,"4,101,160.63"
13,2024-10-01,2024-10-01,TRUE_UP,1,INX150,2821,"104,667.19"
14,2024-10-01,2024-10-01,TRUE_UP,1,INXFEE,20189,"2,144,165.34"
15,2024-10-01,2024-10-01,TRUE_UP,1,INXHIM,5523,"443,174.93"
16,2024-10-01,2024-10-01,TRUE_UP,1,INXLOM,2253,"46,541.99"
17,2024-10-01,2024-10-01,TRUE_UP,1,INXSPC,1161,"38,344.78"
18,2024-10-01,2024-10-01,TRUE_UP,1,MARPRT,3163,"269,257.47"
19,2024-10-01,2024-10-01,TRUE_UP,1,NASIDX,2004,"29,811.76"
20,2024-10-01,2024-10-01,TRUE_UP,26,INDEX,1001,"118,010.91"
21,2024-10-01,2024-10-01,TRUE_UP,26,INX150,216,"3,518.04"
22,2024-10-01,2024-10-01,TRUE_UP,26,INXFEE,193,"16,819.49"
23,2024-10-01,2024-10-01,TRUE_UP,26,INXSPC,64,826.80
24,2024-11-01,2024-11-01,ORIG,1,INDEX,51008,"3,915,438.24"
25,2024-11-01,2024-11-01,ORIG,1,INX150,2834,"238,704.55"
26,2024-11-01,2024-11-01,ORIG,1,INXFEE,20256,"2,134,994.39"
27,2024-11-01,2024-11-01,ORIG,1,INXHIM,5569,"373,021.70"
28,2024-11-01,2024-11-01,ORIG,1,INXLOM,2270,"107,967.35"
29,2024-11-01,2024-11-01,ORIG,1,INXSPC,1157,"24,909.76"
30,2024-11-01,2024-11-01,ORIG,1,MARPRT,3348,"325,747.57"
31,2024-11-01,2024-11-01,ORIG,1,NASIDX,2108,"65,821.66"
32,2024-11-01,2024-11-01,ORIG,26,INDEX,1034,"48,643.87"
33,2024-11-01,2024-11-01,ORIG,26,INX150,225,"3,726.20"
34,2024-11-01,2024-11-01,ORIG,26,INXFEE,200,"15,186.41"
35,2024-11-01,2024-11-01,ORIG,26,INXSPC,64,393.06
36,2024-11-01,2024-11-01,TRUE_UP,1,INDEX,51008,"3,915,618.49"
37,2024-11-01,2024-11-01,TRUE_UP,1,INX150,2834,"238,704.55"
38,2024-11-01,2024-11-01,TRUE_UP,1,INXFEE,20256,"2,178,997.05"
39,2024-11-01,2024-11-01,TRUE_UP,1,INXHIM,5569,"373,021.70"
40,2024-11-01,2024-11-01,TRUE_UP,1,INXLOM,2270,"107,967.35"
41,2024-11-01,2024-11-01,TRUE_UP,1,INXSPC,1157,"24,909.76"
42,2024-11-01,2024-11-01,TRUE_UP,1,MARPRT,3348,"321,788.77"
43,2024-11-01,2024-11-01,TRUE_UP,1,NASIDX,2108,"65,821.66"
44,2024-11-01,2024-11-01,TRUE_UP,26,INDEX,1034,"48,643.87"
45,2024-11-01,2024-11-01,TRUE_UP,26,INX150,225,"3,726.20"
46,2024-11-01,2024-11-01,TRUE_UP,26,INXFEE,199,"15,452.98"
47,2024-11-01,2024-11-01,TRUE_UP,26,INXSPC,64,393.06

In [30]:
hf_credit_summary.to_clipboard(index=False)

In [102]:
inforce_idx_credits_view = None

for hdg_dt, hf_obj in inf_dict.items():

    idx_credit_eff_dt = hf_obj.raw_inforce_df['HedgeDate'].min()
    credit_df = hf_obj.raw_inforce_df
    credit_df = credit_df[credit_df['HedgeDate']==idx_credit_eff_dt]
    credit_df = credit_df.groupby(['HedgeDate', 'Indicator'], as_index=False).agg({'PolicyNum':'count', 'Base_Liab_Ntnl': 'sum', 'Adj_Liab_Ntnl': 'sum', 'Idx_Credit': 'sum'})
    credit_df['Inforce_AsOfDt'] = hdg_dt

    if inforce_idx_credits_view is None:
        inforce_idx_credits_view = credit_df
    else:
        inforce_idx_credits_view = pd.concat([inforce_idx_credits_view, credit_df]).reset_index(drop=True)


cols_ordered = ['Inforce_AsOfDt', 'HedgeDate', 'Indicator', 'PolicyNum', 'Base_Liab_Ntnl', 'Adj_Liab_Ntnl', 'Idx_Credit']
inforce_idx_credits_view = inforce_idx_credits_view[cols_ordered]
inforce_idx_credits_view.rename(columns={'PolicyNum': 'PolicyCount'}, inplace=True)

In [103]:
inforce_idx_credits_view.to_clipboard(index=False)

In [23]:

hf_credit_summary

   Inforce_AsOfDt   HedgeDate  PolicyCount  Base_Liab_Ntnl  Adj_Liab_Ntnl
0      2025-01-02  2024-01-02        91481   58,555,665.68  60,269,646.10
1      2025-01-02  2024-02-01        92613   59,738,832.95  61,046,020.25
2      2025-01-02  2024-03-01        93537   55,548,864.97  57,006,464.75
3      2025-01-02  2024-04-01        94712   55,925,079.27  57,707,624.57
4      2025-01-02  2024-05-01        95533   52,870,910.45  56,815,800.07
..            ...         ...          ...             ...            ...
77     2024-12-02  2024-07-01        97677   63,052,655.94  66,348,904.94
78     2024-12-02  2024-08-01        98210   58,957,980.57  61,640,511.06
79     2024-12-02  2024-09-03        99004   60,257,097.85  61,307,500.49
80     2024-12-02  2024-10-01        99617   69,745,247.97  70,717,961.81
81     2024-12-02  2024-11-01       100596   70,529,136.11  71,991,181.96

[82 rows x 5 columns]

In [25]:
hf_credit_summary.to_clipboard()

# Note: Saved results of to_clipboard() here:
save_file = r'C:\Users\S0053071\Repos\Orion_Process_Backup\Scalar_Calcs\Inforce_Ntnl_OverTime.xlsx'

In [ ]:
list(inf_dict.keys())[0]

In [12]:
inf_dict[list(inf_dict.keys())[0]].inforce_df['ExpiryDt'].unique()

array([datetime.date(2025, 1, 2), datetime.date(2025, 1, 31),
       datetime.date(2025, 2, 28), datetime.date(2025, 4, 1),
       datetime.date(2025, 5, 1), datetime.date(2025, 6, 3),
       datetime.date(2025, 7, 1), datetime.date(2025, 8, 1),
       datetime.date(2025, 9, 3), datetime.date(2025, 10, 1),
       datetime.date(2025, 10, 31), datetime.date(2025, 12, 2)],
      dtype=object)

In [27]:
test_df = inf_dict[list(inf_dict.keys())[0]].inforce_df
test_raw_df = inf_dict[list(inf_dict.keys())[0]].raw_inforce_df

In [15]:
test_df[test_df['ExpiryDt']==date(2025, 1, 2)]

,InforceDt,AsOfDt,CompID,PolicyNum,PHA_Num,Plan,Indicator,Base_Liab_Ntnl,Idx_Credit,HedgeDate,...,Part,Cap,Floor,Spec_Rate,Spread,Asset_Charge,Multiplier,HdgFctr,Strike,Adj_Liab_Ntnl
1,2024-01-01,2024-12-23,1,UE000006,84,1U145500,INX150,230.15,NaN,2024-01-02,...,1.00,0.09,0.01,0.00,0.00,0.00,0.00,0.97,1.01,223.25
14,2024-01-01,2024-12-23,1,UE000006,84,1U145500,INXFEE,271.27,NaN,2024-01-02,...,1.00,10.00,0.00,0.00,0.08,0.00,0.00,0.97,1.08,263.13
27,2024-01-01,2024-12-09,1,UE000011,86,1U145500,INX150,292.83,NaN,2024-01-02,...,1.00,0.09,0.01,0.00,0.00,0.00,0.00,0.97,1.01,284.05
40,2024-01-01,2024-12-09,1,UE000012,84,1U145500,INX150,234.17,NaN,2024-01-02,...,1.00,0.09,0.01,0.00,0.00,0.00,0.00,0.97,1.01,227.14
53,2024-01-01,2024-12-20,1,UE000013,77,1U145500,INX150,61.94,NaN,2024-01-02,...,1.00,0.09,0.01,0.00,0.00,0.00,0.00,0.97,1.01,60.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1248686,2024-01-01,2024-12-28,1,U0982048,1,1U147800,INDEX,"1,093.09",NaN,2024-01-02,...,1.00,0.10,0.00,0.00,0.00,0.00,0.00,0.97,1.00,"1,060.30"
1249189,2024-01-01,2024-12-15,1,U0982129,1,1U147800,INDEX,495.43,NaN,2024-01-02,...,1.00,0.10,0.00,0.00,0.00,0.00,0.00,0.97,1.00,480.57
1249190,2024-01-01,2024-12-15,1,U0982129,1,1U147800,NASIDX,495.43,NaN,2024-01-02,...,1.00,0.10,0.00,0.00,0.00,0.00,0.00,0.97,1.00,480.57
1249191,2024-01-01,2024-12-15,1,U0982130,1,1U147800,INDEX,494.90,NaN,2024-01-02,...,1.00,0.10,0.00,0.00,0.00,0.00,0.00,0.97,1.00,480.05
1249192,2024-01-01,2024-12-15,1,U0982130,1,1U147800,NASIDX,494.91,NaN,2024-01-02,...,1.00,0.10,0.00,0.00,0.00,0.00,0.00,0.97,1.00,480.06

In [16]:
test_df['Idx_Credit'].sum()

np.float64(-0.33)

In [18]:
test_df.groupby('HedgeDate', as_index=False).agg({'PolicyNum':'count', 'Base_Liab_Ntnl': 'sum', 'Adj_Liab_Ntnl': 'sum'})

     HedgeDate  PolicyNum  Base_Liab_Ntnl  Adj_Liab_Ntnl
0   2024-01-02      91481   58,555,665.68  60,269,646.10
1   2024-02-01      92613   59,738,832.95  61,046,020.25
2   2024-03-01      93537   55,548,864.97  57,006,464.75
3   2024-04-01      94712   55,925,079.27  57,707,624.57
4   2024-05-01      95533   52,870,910.45  56,815,800.07
5   2024-06-03      96530   52,527,852.93  54,702,411.38
6   2024-07-01      97451   62,875,785.40  66,162,550.82
7   2024-08-01      97982   58,775,614.71  61,446,256.05
8   2024-09-03      98771   59,036,732.77  60,137,006.81
9   2024-10-01      99381   69,500,233.99  70,467,046.85
10  2024-11-01     100384   70,279,441.22  71,733,087.33
11  2024-12-02     100860   67,850,571.30  69,213,470.10

In [26]:
test_df.columns

Index(['InforceDt', 'AsOfDt', 'CompID', 'PolicyNum', 'PHA_Num', 'Plan',
       'Indicator', 'Base_Liab_Ntnl', 'Idx_Credit', 'HedgeDate', 'ExpiryDt',
       'Product_Detail', 'Product', 'Budget', 'Part', 'Cap', 'Floor',
       'Spec_Rate', 'Spread', 'Asset_Charge', 'Multiplier', 'HdgFctr',
       'Strike', 'Adj_Liab_Ntnl'],
      dtype='object')

In [45]:
idx_credit_dt = test_raw_df['HedgeDate'].min()

In [46]:
test_raw_df[(test_raw_df['Idx_Credit'].notna()) & (test_raw_df['HedgeDate']==idx_credit_dt) ].groupby(['HedgeDate', 'Indicator'], as_index=False).agg({'PolicyNum':'count', 'Idx_Credit': 'sum'})

    HedgeDate Indicator  PolicyNum   Idx_Credit
0  2023-12-01     INDEX      51298 3,455,428.03
1  2023-12-01    INX150       2983   581,564.69
2  2023-12-01    INXFEE      20209 1,656,407.39
3  2023-12-01    INXHIM       5548   400,052.18
4  2023-12-01    INXLOM       2277    79,225.98
5  2023-12-01    INXSPC       1193    21,086.53
6  2023-12-01    MARPRT       3430   254,464.29
7  2023-12-01    NASIDX       2127    78,309.06

datetime.date(2023, 12, 1)

In [35]:
test_raw_df[(test_raw_df['Idx_Credit'].notna()) & (test_raw_df['HedgeDate']==idx_credit_dt) ].groupby(['HedgeDate'], as_index=False).agg({'PolicyNum':'count', 'Idx_Credit': 'sum'})

    HedgeDate  PolicyNum   Idx_Credit
0  2023-12-01      89065 6,526,538.15

In [47]:
idx_credit_df = test_raw_df[(test_raw_df['Idx_Credit'].notna()) & (test_raw_df['HedgeDate']==idx_credit_dt) ].groupby(['HedgeDate', 'Indicator'], as_index=False).agg({'PolicyNum':'count', 'Idx_Credit': 'sum'})

In [90]:
def get_xl_hdr_rng(df: pd.DataFrame):
    return xl_rowcol_to_cell(0,0) + ':' + xl_rowcol_to_cell(0, len(df.columns)-1)

def get_xl_col_rng(df: pd.DataFrame, col_idx: int):
    return xl_rowcol_to_cell(1, col_idx) + ':' + xl_rowcol_to_cell(0, len(df.columns)-1)

def get_xl_rng_for_df(df: pd.DataFrame):
    rows, columns = df.shape
    return xl_rowcol_to_cell(0,0) + ':' + xl_rowcol_to_cell(rows, columns-1)

In [91]:
get_xl_rng_for_df(hf_credit_summary)

'A1:E83'

In [85]:
test_xl_file = r'C:\Users\S0053071\Repos\Orion_Process_Backup\TEST\test_xl_file.xlsx'

# writer = pd.ExcelWriter(test_xl_file, engine='xlsxwriter')

eng_kwargs = {'options': {'strings_to_numbers': True}}

# if_sheet_exists='replace', 

# with pd.ExcelWriter(test_xl_file, engine='xlsxwriter', date_format="yyyy/mm/dd", engine_kwargs=eng_kwargs) as writer:
with pd.ExcelWriter(test_xl_file, engine='xlsxwriter', engine_kwargs=eng_kwargs) as writer:
# with pd.ExcelWriter(test_xl_file, engine='openpyxl', mode='a', engine_kwargs=eng_kwargs) as writer:
# with pd.ExcelWriter(test_xl_file, engine='openpyxl', mode='a') as writer:

    idx_credit_df_sheet = 'Idx_Credits'
    inf_summary_view_sheet = 'Inforce_Summary'
    
    # Get Workbook
    xl_wb =  writer.book
    
    # Add a header format.
    header_format = xl_wb.add_format(
    {
        "border": 0,
        "bold": True,
        "text_wrap": False,
        # "valign": "top",
        "align": "center",
        "bg_color": "#D9D9D9",
        "font_color": "#0070C0",
        # "border": 1,
    })

    # Add a few formats for convenience
    # border_fmt = xl_wb.add_format({"align": "center"})
    date_fmt = xl_wb.add_format({"num_format": "yyyy/mm/dd", "align": "center"})
    non_numeric_fmt = xl_wb.add_format({"align": "center"})
    pct_fmt = xl_wb.add_format({"num_format": "0.00%", "align": "center"})
    num_fmt = xl_wb.add_format({"num_format": "#,##0", "align": "center"})


    dt_flds = ['HedgeDate', 'AsOfDt', 'ExpiryDt', 'InforceDt', 'Inforce_AsOfDt']
    pct_flds = ['Part', 'Cap', 'Cap/Rate', 'Floor',	'Spec_Rate', 'Spread', 'Asset_Charge', 'Multiplier', 'Strike', 'Budget', 'HdgFctr', 'HedgeAssetPct']
    numeric_flds = ['Idx_Credit', 'PolicyNum', 'PolicyCnt', 'PolicyCount', 'Base_Liab_Ntnl', 'Adj_Liab_Ntnl', 'Notional', 'Ntnl']

    def get_fmt_type(col_name):
        if col_name in pct_flds:
            return pct_fmt
        elif col_name in numeric_flds:
            return num_fmt
        elif col_name in dt_flds:
            return date_fmt
        else:
            return non_numeric_fmt
        
    idx_credit_df.to_excel(writer, index=False, header=True, sheet_name=idx_credit_df_sheet, startrow=0 , startcol=0)
    hf_credit_summary.to_excel(writer, index=False, header=True, sheet_name=inf_summary_view_sheet, startrow=0 , startcol=0)

    def write_df_to_sheet_w_fmt(df: pd.DataFrame, sheet_name):

        # Create the sheet and write to it
        df.to_excel(writer, index=False, header=True, sheet_name=sheet_name, startrow=0 , startcol=0)
        # Get Worksheet Object
        xl_ws = writer.sheets[sheet_name]
        # Turn of Gridlines
        xl_ws.hide_gridlines(2)
        # Write the column data with the defined format.
        for col_num, col_name in enumerate(df.columns.values):
            xl_ws.set_column(col_num, col_num, 15, get_fmt_type(col_name))            
            if col_name in dt_flds:
                for row, val in enumerate(df[col_name]):
                    xl_ws.write_datetime(row+1, col_num, val, date_fmt)

        # Format headers
        for col_num, value in enumerate(df.columns.values):            
            xl_ws.write(0, col_num, value, header_format)
            
        #freezing top row 
        xl_ws.freeze_panes(1, 0) 
            
        # Grab the header rng and try to put a border around the rng
        # hdr_rng = xl_rowcol_to_cell(0, 0) + ':' + xl_rowcol_to_cell(0, len(df.columns)-1)                
        # xl_ws.conditional_format(hdr_rng, {'type' : 'no_blanks', 'format' : border_fmt} )        
        # # Set the border around the left side of the hdr
        # border_fmt.set_left(1)
        # xl_ws.conditional_format(hdr_rng.split(':')[0], {'type' : 'no_blanks', 'format' : border_fmt} )
        # border_fmt.set_left(0)        
        # # Set the border around the right side of the hdr
        # border_fmt.set_right(1)
        # xl_ws.conditional_format(hdr_rng.split(':')[1], {'type' : 'no_blanks', 'format' : border_fmt} )
        # border_fmt.set_right(0)


    write_df_to_sheet_w_fmt(idx_credit_df, idx_credit_df_sheet)
    write_df_to_sheet_w_fmt(hf_credit_summary, inf_summary_view_sheet)

    
    # SECTION FOR 1st WORKBOOK
    # xl_ws = xl_wb.get_worksheet_by_name('Idx_Credits')
    # xl_ws = writer.sheets['Idx_Credits']
    # xl_ws.hide_gridlines(2)

    # hdr_rng = xl_rowcol_to_cell(0,0) + ':' + xl_rowcol_to_cell(0, len(idx_credit_df.columns)-1)
    # # Write the column data with the defined format.
    # for col_num, col_name in enumerate(idx_credit_df.columns.values):
    #     xl_ws.set_column(col_num, col_num, 15, get_fmt_type(col_name))
    # # Write the column headers with the defined format.
    # for col_num, value in enumerate(idx_credit_df.columns.values):
    #     xl_ws.write(0, col_num, value, header_format)
    # # Try and put a border around things
    # xl_ws.conditional_format(hdr_rng, {'format' : header_format} )

    # # xl_ws = writer.sheets["Inforce_Summary"]
    # # xl_ws = xl_wb.get_worksheet_by_name('Inforce_Summary')
    # xl_ws = writer.sheets['Inforce_Summary']
    # xl_ws.hide_gridlines(2)

    # Write the column headers with the defined format.
    # for col_num, value in enumerate(inf_summary_view.columns.values):
    #     xl_ws.write(0, col_num, value, header_format)

    

# writer.close()

In [61]:
# hdr_rng = xl_rowcol_to_cell(0,0) + ':' + xl_rowcol_to_cell(0, len(idx_credit_df.columns)-1)
xl_rowcol_to_cell(0,0) + ':' + xl_rowcol_to_cell(0, len(idx_credit_df.columns)-1)

'A1:D1'

In [86]:
df_from_xl_test = pd.read_excel(test_xl_file, sheet_name='Inforce_Summary')

In [87]:
df_from_xl_test

   Inforce_AsOfDt  HedgeDate  PolicyCount  Base_Liab_Ntnl  Adj_Liab_Ntnl
0      2025-01-02 2024-01-02        91481   58,555,665.68  60,269,646.10
1      2025-01-02 2024-02-01        92613   59,738,832.95  61,046,020.25
2      2025-01-02 2024-03-01        93537   55,548,864.97  57,006,464.75
3      2025-01-02 2024-04-01        94712   55,925,079.27  57,707,624.57
4      2025-01-02 2024-05-01        95533   52,870,910.45  56,815,800.07
..            ...        ...          ...             ...            ...
77     2024-12-02 2024-07-01        97677   63,052,655.94  66,348,904.94
78     2024-12-02 2024-08-01        98210   58,957,980.57  61,640,511.06
79     2024-12-02 2024-09-03        99004   60,257,097.85  61,307,500.49
80     2024-12-02 2024-10-01        99617   69,745,247.97  70,717,961.81
81     2024-12-02 2024-11-01       100596   70,529,136.11  71,991,181.96

[82 rows x 5 columns]

In [59]:
idx_credit_df.dtypes

HedgeDate      object
Indicator      object
PolicyNum       int64
Idx_Credit    float64
dtype: object

In [14]:
test_dirs = ['202405']
test_df = process_subdir_hdgfiles(inforce_fldr, files_to_process=test_dirs)
test_df.to_clipboard()

In [50]:
test_fldr = Path(inforce_fldr)
print(test_fldr)

test_process = [f.name for f in test_fldr.iterdir() if f.is_dir()]
test_process

C:\Users\S0053071\Repos\Orion_Process_Backup\HdgRpts_Results

['202307',
 '202308',
 '202309',
 '202310',
 '202311',
 '202312',
 '202401',
 '202402',
 '202403',
 '202404',
 '202405',
 '202406',
 '202407',
 '202408',
 '202409',
 '202410',
 '202411',
 '202412']

In [65]:
test_df['InforceDt']

1          2024-01-01
2          2024-02-01
3          2024-03-01
4          2024-04-01
5          2024-05-01
              ...
1249564    2024-12-01
1249565    2024-12-01
1249566    2024-12-01
1249567    2024-12-01
1249568    2024-12-01
Name: InforceDt, Length: 1159235, dtype: object

In [58]:
full_results_df = process_subdir_hdgfiles(inforce_fldr)

In [59]:
full_results_df

,HedgeFile_Dt,Attrib_Type,HedgeDate,CompID,Indicator,Bbg_Idx,Fund_Name,Opt_Type,Strike,Cap/Rate,Budget,PolicyCount,Base_Liab_Ntnl,Notional
0,2023-07-03,New,2023-07-03,1,NASIDX,NDX Index,NASDAQ-100 1 Yr Pt-to-Pt 100 Part w Cap,Call Spread,1.00,0.10,0.05,20.00,"3,287.51","3,188.88"
1,2023-07-03,New,2023-07-03,1,NASIDX,NDX Index,NASDAQ-100 1 Yr Pt-to-Pt 100 Part w Cap,Call Spread,1.00,0.10,0.05,7.00,"5,043.19","4,891.89"
2,2023-07-03,New,2023-07-03,1,NASIDX,NDX Index,NASDAQ-100 1 Yr Pt-to-Pt 100 Part w Cap,Call Spread,1.00,0.10,0.06,"1,607.00","270,547.46","262,431.04"
3,2023-07-03,New,2023-07-03,1,INDEX,SPX Index,S&P 500 1 Yr Pt-to-Pt 100 Part w Cap,Call Spread,1.00,0.07,0.04,373.00,"171,547.68","166,401.25"
4,2023-07-03,New,2023-07-03,1,INDEX,SPX Index,S&P 500 1 Yr Pt-to-Pt 100 Part w Cap,Call Spread,1.00,0.10,0.05,90.00,"509,891.40","494,594.66"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1783,2024-12-02,Changed,2024-12-02,26,INXFEE,SPX Index,S&P 500 1 Yr Pt-to-Pt Uncapped w Fee,Call,1.09,10.00,0.03,0.00,7.91,6.01
1784,2024-12-02,Changed,2024-12-02,1,INXSPC,SPX Index,S&P 500 1 Yr Specified Rate,Digital,1.00,0.06,0.04,5.00,464.70,441.47
1785,2024-12-02,Changed,2024-12-02,1,INXSPC,SPX Index,S&P 500 1 Yr Specified Rate,Digital,1.00,0.07,0.05,25.00,"8,682.88","8,248.74"
1786,2024-12-02,Changed,2024-12-02,26,INXSPC,SPX Index,S&P 500 1 Yr Specified Rate,Digital,1.00,0.07,0.05,8.00,497.07,377.77
1787,2024-12-02,Changed,2024-12-02,1,MARPRT,SPMARC5P Index,S&P MARC 5% 1 Yr Pt-to-Pt Uncapped,Call,1.00,10.00,0.02,171.00,"72,038.70","163,985.45"

In [61]:
full_results_df.to_clipboard()

In [33]:
# test_sub_dirs = [x[1] for x  in os.walk(results_fldr)]
test_sub_dirs = [x[1] for x in os.walk(inforce_fldr)]
test_sub_dirs = test_sub_dirs[0]

print(test_sub_dirs)

['202307', '202308', '202309', '202310', '202311', '202312', '202401', '202402', '202403', '202404', '202405', '202406', '202407', '202408', '202409', '202410', '202411', '202412']

In [28]:
full_results_df

In [ ]:
test_sub_dir = '202405'
test_dir = os.path.join(inforce_fldr, test_sub_dir)

orig_file = 'iul_liab_summary.csv'
true_file = 'iul_liab_summary_TRUE_UP.csv'

orig_path = os.path.join(test_dir, orig_file)
true_path = os.path.join(test_dir, true_file)

final_cols = ['HedgeFile_Dt', 'Attrib_Type', 'HedgeDate', 'CompID', 'Indicator', 'Bbg_Idx', 'Fund_Name', 'Opt_Type', 'Strike', 'Cap/Rate', 'Budget', 'PolicyCount', 'Base_Liab_Ntnl', 'Notional']
df_cols = ['HedgeDate',	'CompID', 'Indicator', 'Bbg_Idx', 'Fund_Name', 'Opt_Type', 'Strike', 'Cap/Rate', 'Budget', 'PolicyCount', 'Base_Liab_Ntnl', 'Notional']

orig_df = pd.read_csv(orig_path)
orig_df = orig_df[df_cols]

true_df = pd.read_csv(true_path)
true_df = true_df[df_cols]

orig_df['HedgeDate'] = pd.to_datetime(orig_df['HedgeDate']).dt.date
true_df['HedgeDate'] = pd.to_datetime(true_df['HedgeDate']).dt.date
hedge_dt = orig_df['HedgeDate'].max()

In [55]:
test_file = r'G:\MarketRiskMgmt\Pricing Requests\2024-Orion - IUL Hedging\RGA_Process\2_Results\202412\Review Automated VBA\12_2024_HEDGE_ORIG.txt'
hedgefile_colnames = ['CompID', 'PolicyNum', 'Plan', 'IssueDate', 'Indicator', 'Tranx', 'Rev', 'Dept_Desk', 'Entry_Date', 'AsOf_Date', 'Base_Liab_Ntnl', 'Part', 'Cap', 'MGIR_(Cap)', 'Floor', 'Spec_Rate', 'Spread', 'Asset_Charge', 'Multiplier']

test_df = pd.read_csv(test_file, index_col=False, header=None, names=hedgefile_colnames, skipfooter=2, engine='python')

C:\Users\S0053071\AppData\Local\Temp\ipykernel_32400\3241378652.py:4: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  test_df = pd.read_csv(test_file, index_col=False, header=None, names=hedgefile_colnames, skipfooter=2, engine='python')

In [57]:
test_df['Base_Liab_Ntnl'].sum()

np.float64(142757763.13)